pingcap/tidb-dashboard

.github/workflows/release-ui-assets.yaml
Makefile
README.md
ui/.github_release_version
ui/.yarnrc
ui/package.json
ui/src/utils/client/index.js
ui/yarn.lock

- install and use @pingcap-incubator/pd-client-js from GitHub Packages
- update build scripts and related docs

Test use @pingcap-incubator/pd-client-js lib

---

.github/workflows/release-ui-assets.yaml

This PR modifies the GitHub workflow file so that they will also run for PRs. However release actions will be run only for the master branch push.

Run GitHub workflow for PRs

---

ui/src/apps/statement/RootComponent.js
ui/src/apps/statement/StatementListDemo.js
ui/src/apps/statement/app.js
ui/src/apps/statement/components/StatementEnableModal.tsx
ui/src/apps/statement/components/StatementList.tsx
ui/src/apps/statement/components/StatementSettingModal.module.css
ui/src/apps/statement/components/StatementSettingModal.tsx
ui/src/apps/statement/components/StatementsTable.tsx
ui/src/apps/statement/components/index.ts
ui/src/apps/statement/components/statement-types.ts
ui/src/apps/statement/index.js
ui/src/index.js
ui/src/layout/RootComponent.js

- Extract statement components from tidb-foresight as independent components
- Integrate statement components to tidb-dashboard
The final effect:

feat: integrate Statement

---

ui/package.json
ui/src/apps/keyvis/RootComponent.less
ui/src/apps/keyvis/ToolBar.tsx
ui/src/apps/keyvis/app.js
ui/src/apps/keyvis/heatmap/legend.ts
ui/yarn.lock

refactor: replace semantic-ui-react components by antd

---

Makefile
cmd/tidb-dashboard/main.go
go.mod
go.sum
pkg/apiserver/info/info.go
pkg/config/config.go
pkg/utils/info.go

* Use Context and WaitGroup to exit gracefully
* Use LDFLAGS in makefile to get version information

add Context and WaitGroup in Config

---

ui/.yarnrc
ui/package.json
ui/src/apps/statement/RootComponent.js
ui/src/apps/statement/StatementDetailDemo.js
ui/src/apps/statement/StatementListDemo.js
ui/src/apps/statement/components/HorizontalBar.tsx
ui/src/apps/statement/components/StatementDetail.module.css
ui/src/apps/statement/components/StatementDetail.tsx
ui/src/apps/statement/components/StatementDetailTable.tsx
ui/src/apps/statement/components/StatementSummaryTable.tsx
ui/src/apps/statement/components/StatementsTable.tsx
ui/src/apps/statement/components/index.ts
ui/src/apps/statement/components/statement-types.ts
ui/yarn.lock

- Add horizontal visual color bars for table columns
- Implement the statement detail components
PTAL

Implement statement detail page

---

pkg/keyvisual/service.go
pkg/keyvisual/storage/region.go

* Change some unnecessary log levels to Debug

keyvisual: change log level

---

pkg/pd/etcd.go

keyvisual: fix constant error

---

pkg/apiserver/statement/models.go
pkg/apiserver/statement/queries.go
pkg/apiserver/statement/statement.go

This PR simplifies the statement query.

Simplify statement queries

---

cmd/tidb-dashboard/main.go
pkg/keyvisual/decorator/tidb_requests.go
pkg/keyvisual/region/interface.go
pkg/pd/etcd.go
pkg/tidb/forwarder.go

PD only provides an EtcdProvider, instead of Etcd instance.

Accept EtcdProvider for TiDBForwarder

---

.golangci.yml
pkg/apiserver/clusterinfo/fetch.go
pkg/apiserver/clusterinfo/service.go
pkg/utils/clusterinfo/clusterinfo.go
pkg/utils/clusterinfo/fetcher.go

Simplify code base

---

pkg/apiserver/diagnose/report.go

sql-diagnosis

---

pkg/apiserver/diagnose/report.go

Sql diagnosis

---

pkg/apiserver/user/auth.go
pkg/apiserver/utils/tidb_conn.go
pkg/tidb/conn.go
pkg/tidb/forwarder.go

fix #95 
Solve the problem that Dashboard can still login when the IP reported by TiDB is `0.0.0.0`.

tidb: catch all errors

---

pkg/apiserver/profiling/model.go
pkg/apiserver/profiling/profile.go
pkg/apiserver/profiling/router.go

This PR adds the custom grab interval for profiling.

profiling: support custom grab interval for profiling

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/usability-challenge-program.md

* add `usability-challenge-program.md`

Add Usability Challenge Program issue template

---

ui/src/apps/clusterInfo/components/MonitorAlertBar.js

Signed-off-by: mapleFU <1506118561@qq.com>

clusterinfo frontend: Add warning of am and grafana

---

cmd/tidb-dashboard/main.go
pkg/keyvisual/service.go

Key Visualizer can be started and closed separately.

keyvisual: control start and stop

---

CONTRIBUTING.md
README.md

Preview → https://github.com/Deardrops/tidb-dashboard/blob/contributing/CONTRIBUTING.md

document: add contributing guide

---

pkg/apiserver/diagnose/report.go

Signed-off-by: crazycs <crazycs520@gmail.com>

add check before report

---

ui/src/apps/clusterInfo/RootComponent.js
ui/src/apps/clusterInfo/RootComponent.module.less
ui/src/apps/clusterInfo/components/ClusterInfoTable.js
ui/src/apps/clusterInfo/components/ComponentPanel.js
ui/src/apps/clusterInfo/components/ComponentPanel.module.less
ui/src/apps/clusterInfo/components/MonitorAlertBar.js
ui/src/apps/clusterInfo/components/MonitorAlertBar.module.less
ui/src/apps/clusterInfo/translations/en.yaml
ui/src/apps/clusterInfo/translations/zh-CN.yaml

Improve ClusterInfo Looking

---

ui/src/apps/diagnose/components/DiagnoseGenerator.tsx

Show error message when generating report API meets error.

diagnosis: show error message when generating report meets error

---

pkg/apiserver/profiling/model.go
pkg/apiserver/profiling/profile.go
pkg/apiserver/profiling/router.go
ui/src/apps/nodeProfiling/pages/Detail.js
ui/src/apps/nodeProfiling/pages/Index.js
ui/src/apps/nodeProfiling/translations/en.yaml
ui/src/apps/nodeProfiling/translations/zh-CN.yaml
ui/src/index.js

Profiling duration can be selected:
Profiling progress is supported:
Based on https://github.com/pingcap-incubator/tidb-dashboard/pull/127

Profiling duration and progress UI

---

go.mod
pkg/apiserver/logsearch/service.go
pkg/apiserver/utils/jwt.go
ui/src/apps/logSearching/components/SearchProgress.tsx

logs: add authentication support for log searching API

---

pkg/apiserver/diagnose/diagnose.go
pkg/apiserver/info/info.go
pkg/apiserver/statement/statement.go
pkg/apiserver/utils/tidb_conn.go

Provide new functions:
- GetTiDBConnection
- TakeTiDBConnection

Add utils to extend TiDB connection life time

---

ui/src/apps/keyvis/RootComponent.less
ui/src/apps/keyvis/heatmap/chart.ts

Improve KeyVis tooltip

---

pkg/apiserver/diagnose/compare.go
pkg/apiserver/diagnose/report.go

Signed-off-by: crazycs <crazycs520@gmail.com>

add comment for compare report.

---

pkg/apiserver/diagnose/compare.go
pkg/apiserver/diagnose/query.go
pkg/apiserver/diagnose/report.go

related PR: https://github.com/pingcap/tidb/pull/15210

diagnose: fix cpu usage bug and refine report format 

---

pkg/pd/etcd.go

update etcd config to fix #58 #69 
* add `AutoSyncInterval`, `DialTimeout`, `ConnectParams`, `KeepaliveParams`, `LogConfig` in etcd config.

pd: update etcd config

---

CONTRIBUTING.md

Signed-off-by: zhongzc <zhongzc_arch@outlook.com>
- update tiup command
- point out a common problem

contribution: complement the Contributing.md

---

ui/src/apps/keyvis/heatmap/chart.ts

Fix frame selection failure due to y-axis reverse.

keyvisual: fix select & zoom bug

---

ui/src/layout/main/RootComponent.js
ui/src/layout/main/RootComponent.module.less
ui/src/layout/main/Sider.js
ui/src/layout/main/Sider.module.less

Currently there is no sider toggle animation. This PR fixes it.

ui: Fix sider animation

---

pkg/apiserver/apiserver.go
pkg/keyvisual/service.go

*: prevent repeated start/stop

---

pkg/http/http.go
pkg/pd/etcd.go

The server left some thread after stop, causing leak.

*: close http client and etcd client when the server stop

---

ui/.github_release_version

bump ui version

---

ui/src/apps/searchLogs/LogSearchingDetail.js
ui/src/apps/searchLogs/LogSearchingHistory.js
ui/src/apps/searchLogs/components/SearchHistory.tsx
ui/src/apps/searchLogs/components/SearchResult.tsx

logs: refine search_logs page

---

pkg/utils/clusterinfo/fetcher.go

This pr fix add prefix for tikv version.

clusterinfo: Fixing TiKV version for tidb-dashboard

---

pkg/utils/service_status.go

*: abort when service is stopped

---

pkg/apiserver/apiserver.go

HandleContext was called incorrectly, causing the handler to execute twice.

*: fix duplicate handler bug

---

ui/.github_release_version

bump ui (20200327_1)

---

ui/src/apps/diagnose/components/DiagnoseGenerator.tsx
ui/src/apps/diagnose/translations/en.yaml
ui/src/apps/diagnose/translations/zh-CN.yaml

ui: Customize diagnose duration

---

go.mod
go.sum
scripts/embed_ui_assets.sh
tools.go

update the version of dependency: go-bindata

use go-bindata v3

---

pkg/apiserver/diagnose/diagnose.go

change compare report call

---

pkg/apiserver/diagnose/compare.go
pkg/apiserver/diagnose/report.go
pkg/apiserver/diagnose/report_test.go

* Change the `diff_ratio` calculation from `(v1-v2)/max(v1,v2)` to `if v2 > v1 => { v2 / v1 - 1 } else => { 1 - v1 / v2 }`
* remove duplicate row in `Max diff item` table.
* Add `VALUE_TYPE` in `Max diff item` table.
Before
This PR

diagnose: refine compare ratio calculation and compare report

---

ui/packages/keyvis/package.json
ui/packages/keyvis/src/components/KeyVis.tsx
ui/packages/keyvis/src/components/ToolBar.tsx
ui/packages/keyvis/src/translations/en.yaml
ui/packages/keyvis/src/translations/zh-CN.yaml
ui/yarn.lock

Improve KeyViz auto refresh

---

pkg/keyvisual/storage/region.go
ui/.github_release_version

Noise data occasionally exist in the data, which is characterized by a very large value. A wash operation was performed on this part of the data. However, in actual use, the normal reading flow is very easy to exceed this value. Therefore, consider changing the strategy to use write flow and increase the threshold.

dashboard: adjust wash strategy and bump ui

---

ui/packages/dashboard_components/src/Card/index.js
ui/packages/dashboard_components/src/CardTable/index.js
ui/packages/dashboard_components/src/Head/index.js

UCP #105 
This close #105 issue partly.
Refactor the class components to function components for `packages/dashboard_components/*`.
Improvement

UCP105 :refactor the class components to function components for packages/dashboard_components/*

---

ui/src/layout/signin/RootComponent.js

UCP #105
This close #105 issue partly.
Refactor the class components to function components for `src/layout/signin`.
Improvement

UCP105 :refactor the class components to function components for src/layout/signin

---

ui/src/layout/signin/RootComponent.js

Fix bug in https://github.com/pingcap-incubator/tidb-dashboard/pull/338, set second parameter in `useEffect` with empty array .
Bug fix

*: fix useEffect second parameter in layout/login

---

pkg/apiserver/statement/models.go
pkg/apiserver/statement/queries.go
pkg/apiserver/statement/statement.go
ui/packages/statement/package.json
ui/packages/statement/src/components/StatementsOverview.tsx

UCP https://github.com/pingcap-incubator/tidb-dashboard/issues/334

Use timestamp instead of string

---

pkg/apiserver/statement/queries.go
pkg/apiserver/statement/statement.go
ui/lib/apps/Statement/components/StatementsOverview.tsx
ui/lib/apps/Statement/components/search-options-context.ts
ui/lib/apps/Statement/index.tsx
ui/lib/apps/Statement/pages/StatementsOverviewPage.tsx
ui/lib/apps/Statement/translations/en.yaml
ui/lib/apps/Statement/translations/zh-CN.yaml

Filter statements by sql type

---

ui/lib/apps/Overview/index.js
ui/lib/components/CardTableV2/index.tsx

fix TopN statements

---

ui/lib/apps/Overview/index.js
ui/lib/apps/Statement/components/StatementsOverview.tsx
ui/lib/apps/Statement/components/StatementsTable.tsx
ui/lib/apps/Statement/translations/en.yaml
ui/lib/apps/Statement/translations/zh-CN.yaml
ui/lib/components/CardTableV2/index.tsx

What did:
- Support show or hide some columns
- Support show full or ellipsis SQL
- Refine tooltip for column headers
- Refine tooltip wording
Thanks for the great `CardTableV2.renderColumnVisibilitySelection()` method.
More metrics will add in the later PR.

Filter columns

---

ui/lib/apps/Overview/index.js
ui/lib/apps/Statement/components/StatementSettingForm.tsx
ui/lib/apps/Statement/components/StatementsOverview.tsx
ui/lib/apps/Statement/components/StatementsTable.tsx
ui/lib/apps/Statement/translations/en.yaml
ui/lib/apps/Statement/translations/zh-CN.yaml
ui/lib/apps/Statement/utils/commonColumns.tsx
ui/lib/components/CardTableV2/index.tsx

Filter columns and fix TopN Statements

---

pkg/apiserver/statement/queries.go
ui/lib/apps/Statement/components/StatementsOverview.tsx
ui/lib/apps/Statement/components/TimeRangeSelector.module.less
ui/lib/apps/Statement/components/TimeRangeSelector.tsx
ui/lib/apps/Statement/translations/en.yaml
ui/lib/apps/Statement/translations/zh-CN.yaml

This PR will change to merge to master after #382 is merged.

Statement time range selector

---

pkg/apiserver/statement/models.go
pkg/apiserver/statement/queries.go
ui/lib/apps/Overview/index.js
ui/lib/apps/Statement/components/StatementsTable.tsx
ui/lib/apps/Statement/translations/en.yaml
ui/lib/apps/Statement/translations/zh-CN.yaml
ui/lib/apps/Statement/utils/useColumn.tsx

What did:
- Add errors/warnings, parse latency, compile latency, copr columns

Add more columns for statements

---

pkg/keyvisual/decorator/tidb.go
pkg/keyvisual/decorator/tidb_requests.go

keyviz: skip update TableMap if the schema version has not changed

---

pkg/utils/clusterinfo/clusterinfo.go
pkg/utils/clusterinfo/fetcher.go
ui/lib/apps/ClusterInfo/components/InstanceTable.js
ui/lib/apps/ClusterInfo/translations/en.yaml
ui/lib/apps/ClusterInfo/translations/zh-CN.yaml

Please merge this pr after pingcap/pd#2361 is merged

(reopen 344)clusterinfo: Allow fetching git hash in tidb-cluster backend

---

ui/lib/apps/SlowQuery/components/Detail.tsx

slow_query: fix bugs in slow query page

---

ui/lib/apps/SlowQuery/components/List.module.less
ui/lib/apps/SlowQuery/components/List.tsx
ui/lib/apps/Statement/components/StatementsOverview.tsx
ui/lib/apps/Statement/components/styles.module.less

Make header works for small screen

---

pkg/config/dynamic_config.go
pkg/keyvisual/manager.go

Since it is not yet possible to control the start of keyviz through the front end, keyviz is currently started by default.

enabled keyviz by default && bump ui

---

pkg/config/dynamic_config.go
pkg/keyvisual/manager.go
pkg/keyvisual/matrix/distance.go
ui/.github_release_version
ui/lib/apps/KeyViz/components/KeyViz.less
ui/lib/apps/KeyViz/components/KeyViz.tsx
ui/lib/apps/KeyViz/components/KeyVizSettingForm.tsx
ui/lib/apps/KeyViz/components/ToolBar.tsx
ui/lib/apps/KeyViz/heatmap/chart.ts
ui/lib/apps/KeyViz/translations/en.yaml
ui/lib/apps/KeyViz/translations/zh-CN.yaml
ui/lib/apps/KeyViz/utils/api.ts

* revert #402 (so keyviz is disabled by default)
* support to modify the config through the front-end
* bump ui

keyviz: support to modify the config through the front-end && bump ui

---

ui/lib/apps/SlowQuery/components/Detail.tsx
ui/lib/apps/SlowQuery/components/List.tsx
ui/lib/apps/SlowQuery/components/TimeRangeSelector.tsx

slow query: save search options by session storage

---

ui/lib/apps/Overview/index.tsx
ui/lib/apps/SlowQuery/components/List.tsx
ui/lib/apps/SlowQuery/components/SlowQueriesTable.tsx
ui/lib/apps/SlowQuery/components/TimeRangeSelector.tsx

overview: show recent slow quries

---

.github/workflows/e2e-test.yaml
pkg/config/dynamic_config_manager.go
pkg/keyvisual/manager.go
ui/.github_release_version

* dynamic_config: retry load when starting
* make tiflash is not started in e2e test
* bump ui

dynamic_config: retry load when starting && bump ui

---

pkg/apiserver/apiserver.go
pkg/apiserver/info/info.go
pkg/apiserver/logsearch/models.go
pkg/apiserver/logsearch/service.go
pkg/apiserver/model/common_models.go
pkg/apiserver/profiling/model.go
pkg/apiserver/profiling/profile.go
pkg/apiserver/profiling/router.go
pkg/apiserver/profiling/service.go
pkg/config/dynamic_config.go
pkg/config/dynamic_config_manager.go
pkg/http/http.go
pkg/keyvisual/decorator/tidb.go
pkg/keyvisual/manager.go
pkg/keyvisual/matrix/distance.go
pkg/keyvisual/matrix/plane.go
pkg/keyvisual/service.go
pkg/keyvisual/storage/stat.go
ui/lib/apps/SearchLogs/components/SearchHeader.tsx
ui/lib/apps/SearchLogs/components/SearchHistory.tsx
ui/lib/apps/SearchLogs/components/SearchResult.tsx
ui/lib/apps/SearchLogs/components/utils.ts

This PR supports auto profiling through dynamic config.

profiling: support auto collection

---

ui/lib/apps/KeyViz/components/KeyViz.tsx
ui/lib/apps/KeyViz/components/KeyVizSettingForm.tsx
ui/lib/apps/KeyViz/translations/en.yaml
ui/lib/apps/KeyViz/translations/zh-CN.yaml
ui/lib/apps/KeyViz/utils/api.ts
ui/lib/utils/form.ts

Implement the front-end of #442 
Note: hide `Policy` in the production environment

keyviz: update settings page

---

ui/lib/apps/InstanceProfiling/pages/Detail.js
ui/lib/apps/SlowQuery/components/SlowQueriesTable.tsx
ui/lib/apps/Statement/components/StatementsTable.tsx
ui/lib/apps/Statement/pages/Detail/index.tsx

instance_profiling: fix detail page crash

---

ui/lib/apps/SlowQuery/components/SlowQueriesTable.tsx
ui/lib/apps/Statement/components/StatementsTable.tsx
ui/lib/components/CardTableV2/index.tsx

move onGetColumns props out of CardTableV2

---

ui/lib/apps/Diagnose/components/DiagnoseGenerator.tsx
ui/lib/apps/Diagnose/components/DiagnoseHistory.tsx
ui/lib/apps/Diagnose/components/DiagnoseStatus.tsx
ui/lib/apps/InstanceProfiling/pages/Detail.tsx

What did:
- Use useClientRequestWithPolling replace setInterval
- Fix diagnosis history show wrong created time (always show current time)

diagnose: use useClientRequestWithPolling replace setInterval

---

pkg/apiserver/clusterinfo/service.go
pkg/apiserver/logsearch/scheduler.go
pkg/apiserver/logsearch/service.go
pkg/apiserver/logsearch/task.go
pkg/apiserver/metrics/metrics.go
pkg/apiserver/profiling/router.go
pkg/apiserver/profiling/service.go
pkg/config/dynamic_config_manager.go
pkg/keyvisual/manager.go
pkg/tidb/forwarder.go

* config: dynamic config loading without blocking start
* refine the use of context

config: dynamic config loading without blocking start

---

pkg/apiserver/logsearch/task.go

log-seach: only search slow log on TiKV

---

pkg/apiserver/logsearch/pack.go
pkg/apiserver/logsearch/task.go
ui/lib/apps/SlowQuery/utils/tableColumns.tsx

Some tiny improvements for log search

---

pkg/config/config.go
pkg/tidb/forwarder.go
pkg/tidb/proxy.go
pkg/tidb/proxy_test.go

* config: remove `CheckInterval `
* forwarder: refine the use of context
* forwarder: speed up startup

forwarder: fix some bugs

---

pkg/apiserver/diagnose/report.go
ui/diagnoseReportApp/translations/en.yaml
ui/diagnoseReportApp/translations/zh-CN.yaml

diagnose: fix typo

---

ui/lib/apps/ClusterInfo/components/HostTable.tsx
ui/lib/apps/SearchLogs/components/Log.tsx
ui/lib/apps/SearchLogs/components/SearchResult.tsx
ui/lib/apps/SearchLogs/components/Styles.module.css
ui/lib/components/CardTableV2/index.module.less
ui/lib/components/CardTableV2/index.tsx
ui/lib/utils/tableColumns.tsx

Fix some known issues

---

ui/.github_release_version

bump ui to 20200514_1

---

ui/lib/apps/SearchLogs/LogSearching.tsx
ui/lib/apps/SearchLogs/LogSearchingDetail.tsx
ui/lib/apps/SearchLogs/components/SearchHeader.tsx
ui/lib/apps/SearchLogs/components/SearchHistory.tsx
ui/lib/apps/SearchLogs/components/SearchProgress.tsx
ui/lib/apps/SearchLogs/components/SearchResult.module.css
ui/lib/apps/SearchLogs/components/SearchResult.tsx
ui/lib/apps/SearchLogs/components/Styles.module.css
ui/lib/apps/SearchLogs/index.tsx

What did
- hidden overflow content
- sticky table header
This PR will help resolve #491 with PR #497 
Before:
After:
Update:

search_logs: refine search result table

---

pkg/config/dynamic_config_manager.go
pkg/tidb/conn.go
pkg/tidb/forwarder.go
pkg/tidb/proxy.go

* *: refine the use of backoff with WithContext and Permanent
* tidb_forwarder: refine deduplication and sleep

refine the use of backoff and fix tidb_forwarder bug

---

pkg/apiserver/profiling/profile.go

using a blank ui to eliminate the pprof logs

---

ui/dashboardApp/layout/translations/en.yaml
ui/lib/apps/ClusterInfo/translations/en.yaml
ui/lib/apps/ClusterInfo/translations/zh-CN.yaml
ui/lib/apps/Diagnose/translations/en.yaml
ui/lib/apps/Diagnose/translations/zh-CN.yaml
ui/lib/apps/InstanceProfiling/translations/en.yaml
ui/lib/apps/InstanceProfiling/translations/zh-CN.yaml
ui/lib/apps/Overview/translations/zh-CN.yaml
ui/lib/apps/SearchLogs/translations/en.yaml

Signed-off-by: Breezewish <hi@breeswish.org>

Fix remaining I18N issues

---

ui/.github_release_version
ui/lib/apps/ClusterInfo/translations/en.yaml
ui/lib/apps/Overview/translations/en.yaml
ui/lib/apps/Overview/translations/zh-CN.yaml
ui/lib/apps/SearchLogs/components/Log.tsx
ui/lib/apps/SearchLogs/components/SearchHeader.tsx
ui/lib/apps/SearchLogs/components/SearchProgress.tsx
ui/lib/apps/SearchLogs/components/SearchResult.tsx
ui/lib/apps/SearchLogs/components/Styles.module.less
ui/lib/apps/SlowQuery/pages/Detail/DetailTabBasic.tsx
ui/lib/apps/SlowQuery/pages/Detail/DetailTabCopr.tsx
ui/lib/apps/SlowQuery/pages/Detail/DetailTabTime.tsx
ui/lib/apps/SlowQuery/pages/Detail/DetailTabTxn.tsx
ui/lib/apps/SlowQuery/translations/en.yaml
ui/lib/apps/SlowQuery/translations/zh-CN.yaml
ui/lib/apps/SlowQuery/utils/tableColumns.tsx
ui/lib/apps/Statement/pages/Detail/PlanDetailTabBasic.tsx
ui/lib/apps/Statement/pages/Detail/PlanDetailTabCopr.tsx
ui/lib/apps/Statement/pages/Detail/PlanDetailTabTime.tsx
ui/lib/apps/Statement/pages/Detail/PlanDetailTabTxn.tsx
ui/lib/apps/Statement/translations/en.yaml
ui/lib/apps/Statement/translations/zh-CN.yaml
ui/lib/components/TextWithInfo/index.tsx
ui/lib/utils/tableColumns.tsx

Update text highlight color

---

ui/lib/apps/Overview/index.tsx
ui/lib/apps/SlowQuery/pages/List/index.tsx
ui/lib/apps/SlowQuery/utils/useSlowQuery.ts
ui/lib/apps/Statement/pages/List/index.tsx
ui/lib/apps/Statement/utils/useStatement.ts
ui/lib/components/CardTableV2/index.tsx
ui/lib/components/MetricChart/index.tsx
ui/lib/utils/apiErrorsMsg.ts

Handle errors for statement / slow query / metric

---

pkg/config/dynamic_config.go
pkg/keyvisual/decorator/tidb.go
pkg/keyvisual/decorator/tidb_requests.go
pkg/keyvisual/manager.go
pkg/tidb/model/codec.go
pkg/tidb/model/codec_test.go
pkg/tidb/model/model.go
ui/lib/apps/ClusterInfo/index.tsx
ui/lib/apps/KeyViz/components/KeyViz.tsx
ui/lib/apps/KeyViz/components/KeyVizSettingForm.tsx
ui/lib/apps/SearchLogs/components/SearchProgress.tsx
ui/lib/apps/SearchLogs/pages/LogSearchHistory.tsx
ui/lib/apps/Statement/pages/List/StatementSettingForm.tsx
ui/lib/apps/UserProfile/index.tsx
ui/package.json
ui/yarn.lock

* update antd to v4.2.5
* keyviz: enabled by default
* keyviz: support partition table

keyviz: enabled by default and support partition table

---

pkg/tidb/forwarder.go

* forwarder: fix unlimited log bug

forwarder: fix unlimited log bug

---

pkg/keyvisual/decorator/tidb_requests.go

* keyviz: update schema version after success

keyviz: update schema version after success

---

ui/.github_release_version
ui/dashboardApp/publicPathPrefix.ts

Allow publicPath to be root

---

ui/lib/apps/KeyViz/components/KeyViz.less
ui/lib/apps/KeyViz/heatmap/chart.ts

* Before
`employees_nor...`
* After
`employees_normal_abcdefghijklmnopqrstuvwxyz`

keyviz: fix the bug that the copied text is incomplete

---

pkg/apiserver/apiserver.go
pkg/keyvisual/service.go
pkg/utils/service_status.go

Prevent race in PD test [#2464](https://github.com/pingcap/pd/issues/2464)

*: handle Service starting error

---

ui/.github_release_version
ui/dashboardApp/layout/main/Sider/Banner.js

* update display version to 4.0.1
* bump ui to 20200603_1

update display version and bump ui

---

ui/.github_release_version
ui/lib/apps/SlowQuery/translations/zh-CN.yaml

Fix text typo

---

pkg/uiserver/embedded_assets_rewriter.go

Update mod time during rewrite
fix #603

uiserver: update mod time

---

pkg/apiserver/clusterinfo/service.go
pkg/utils/topology/pd.go
pkg/utils/topology/store.go
pkg/utils/topology/tidb.go

Fix wrong sort orders for TiDB & PD instances and Hosts

Fix incorrect sort orders

---

ui/lib/apps/Diagnose/pages/DiagnoseGenerator.tsx
ui/lib/apps/SearchLogs/components/SearchResult.tsx
ui/lib/components/DatePicker/index.tsx
ui/lib/components/TimeRangeSelector/index.tsx
ui/lib/components/index.ts
ui/package.json

closes https://github.com/pingcap-incubator/tidb-dashboard/issues/181

ui: replace momentjs with dayjs

---

docs/.markdownlint.json
docs/rfcs/20200615-template.md
scripts/lint.sh

Signed-off-by: Breezewish <hi@breeswish.org>

Create RFCs directory

---

.github/workflows/e2e-test.yaml
ui/lib/utils/telemetry.ts

Fix the bug that telemetry still report data when disabling telemetry.

fix telemetry

---

ui/.github_release_version
ui/dashboardApp/layout/main/Sider/Banner.tsx

- Update dashboard version to 4.0.2 manually

update dashboard version and bump ui

---

ui/.github_release_version
ui/dashboardApp/layout/main/Sider/index.tsx
ui/lib/apps/SearchLogs/components/SearchResult.tsx

Signed-off-by: Breezewish <hi@breeswish.org>

Hide debug menu in production

---

pkg/apiserver/statement/queries.go
pkg/apiserver/statement/statement.go
ui/lib/apps/Statement/pages/List/index.tsx
ui/lib/apps/Statement/utils/useStatement.ts

statements: support search

---

pkg/http/http.go
pkg/tidb/forwarder.go

tidb: generate the scheme with the correct TLS config

---

ui/lib/apps/SearchLogs/components/SearchHeader.tsx
ui/lib/apps/SearchLogs/components/SearchResult.tsx
ui/lib/components/InstanceSelect/TableWithFilter.tsx
ui/lib/components/TimeRangeSelector/index.tsx
ui/tests/e2e/search_log.test.ts
ui/tests/e2e/test_config.ts

fix e2e test

---

pkg/apiserver/statement/queries.go

There was a type that jumped out at my while reading the code.

pkg/apiserver/statement: fix typo

---

ui/lib/apps/SearchLogs/components/SearchHeader.tsx

Fix https://github.com/pingcap-incubator/tidb-dashboard/issues/669

Fix bug that TiFlash logs cannot be searched

---

ui/lib/utils/telemetry.ts

report dashboard internal version

---

ui/lib/apps/Diagnose/pages/DiagnoseGenerator.tsx

Fix the bug that it jumps to an empty page when start to diagnose

fix diagnose router

---

release-version
ui/lib/apps/Diagnose/pages/DiagnoseGenerator.tsx

telemetry: fix diagnose router (#726)

Release v2020.08.07.1

---

ui/lib/apps/SearchLogs/components/SearchResult.tsx
ui/lib/apps/SearchLogs/index.meta.ts

log_search: Display port in log search results

---

ui/lib/apps/DataManager/index.tsx
ui/lib/apps/DataManager/pages/DBTableList.tsx
ui/lib/apps/DataManager/pages/TableDataView.tsx
ui/lib/apps/DataManager/translations/en.yaml
ui/lib/apps/DataManager/translations/zh.yaml
ui/lib/apps/UsersManager/pages/DBUserList.tsx

- select table row
- insert table row
- update table row
- delete table row
@baurine @breeswish PTAL

add manage table data

---

.github/workflows/release.yaml

Signed-off-by: lihaowei <haoweili35@gmail.com>
Fix for issue #715

Add action to check release version is changed for release branch

---

pkg/keyvisual/matrix/axis.go
pkg/keyvisual/matrix/axis_test.go
release-version
ui/dashboardApp/index.ts

* ui: display error message instead of stack trace on connect failure (#769)
* keyviz: fix panic in matrix package (#773)

Release v2020.10.21.1

---

.github/workflows/e2e-test.yaml
.github/workflows/pr-build.yaml
.github/workflows/release-check.yaml
.github/workflows/release.yaml

build: add action to check release-version is changed for release branch

---

ui/lib/apps/Overview/index.tsx
ui/yarn.lock

use qps instead of ops as the unit in QPS graph
fix #779

fix: use qps instead of ops

---

ui/lib/apps/KeyViz/components/KeyVizSettingForm.tsx
ui/lib/apps/KeyViz/translations/en.yaml
ui/lib/apps/KeyViz/translations/zh.yaml

Add keyviz enable tips for better user understanding.

tweak(keyviz): add enable tips

---

ui/lib/apps/DebugAPI/apilist/ApiList.tsx
ui/lib/apps/DebugAPI/translations/en.yaml
ui/lib/apps/DebugAPI/translations/zh.yaml

ui: Add a warning for the debug API

---

ui/lib/components/DateTime/Calendar.tsx
ui/lib/components/DateTime/calendarPlugin.ts

tweak(ui): support `sameWeek` format

---

.github/workflows/release.yaml

Same as the title. PTAL.
/cc @breeswish

Create multi branch PRs to pd

---

.github/workflows/release.yaml
release-version

- Create multi branch PRs to pd (#951)

Release v2021.07.09.1

---

pkg/utils/distro/default_distro_info.go
pkg/utils/distro/distro.go

Update distro resource type to map[string]string.

Refine distro resource type

---

scripts/replace_distro_resource.sh
ui/lib/apps/UserProfile/translations/en.yaml
ui/lib/apps/UserProfile/translations/zh.yaml

The landing image on the signin page should be replaceable.

feat: replaceable landing image

---

ui/lib/apps/SearchLogs/components/SearchResult.tsx
ui/lib/components/DateTime/Calendar.tsx
ui/lib/components/DateTime/Long.tsx

Related: #973 . Add timezone information.
covered cases:
- table field
- tooltip
not covered:
- form value (unnecessary)
- chart value (should be shorter and clearer)

feat(ui): add timezone information

---

pkg/apiserver/user/auth.go
pkg/apiserver/user/sqlauth/sqlauth.go
pkg/apiserver/user/sso/models.go
pkg/apiserver/user/sso/service.go
pkg/apiserver/user/verify_sql_user.go
pkg/apiserver/user/verify_sql_user_test.go
ui/lib/apps/UserProfile/Form.SSO.tsx
ui/lib/apps/UserProfile/translations/en.yaml
ui/lib/apps/UserProfile/translations/zh.yaml

What did:
- Support modify authorization at any time
- Support authorize to non-root user to login by sso
Demo:

support authorize non root user to sso login

---

ui/dashboardApp/layout/signin/index.tsx
ui/dashboardApp/layout/translations/en.yaml
ui/dashboardApp/layout/translations/zh.yaml
ui/lib/client/index.tsx
ui/lib/client/translations/en.yaml
ui/lib/client/translations/zh.yaml

add doc link for insufficient privileges error

---

pkg/apiserver/user/verify_sql_user.go

Currently, if TiDB enables the `security.skip-grant-table`, running `show grants` and some other SQL statements will get errors, so we temporarily skip the grants check if `skip-grant-table` is enabled.

skip grant check when skip-grant-table enable

---

ui/dashboardApp/layout/main/Sider/index.tsx
ui/dashboardApp/layout/signin/index.tsx
ui/lib/apps/ContinuousProfiling/pages/ConProfSettingForm.tsx
ui/lib/apps/ContinuousProfiling/translations/en.yaml
ui/lib/apps/ContinuousProfiling/translations/zh.yaml

What did:
- Make the left side menu active for `instance_profiling` and `continuous_profiling` after refreshing
- Fix the profile retention duration select options
- Remember the last login username
Screenshots:

more refines

---

ui/lib/client/translations/en.yaml
ui/lib/client/translations/zh.yaml

update conprof wording

---

ui/lib/apps/ContinuousProfiling/translations/en.yaml
ui/lib/apps/InstanceProfiling/translations/en.yaml

What did:
- Refine i18n wording
Screenshots:

conprof misc refines

---

.github/workflows/release-check.yaml
.github/workflows/release.yaml
pkg/apiserver/profiling/fetcher.go
pkg/httpc/client.go
pkg/httpc/client_test.go
pkg/keyvisual/storage/model.go
pkg/keyvisual/storage/model_test.go
pkg/pd/client.go
pkg/pd/client_test.go
release-version

Release branch for 4.0, 5.0, 5.1

Release v2021.09.02.r40.1

---

ui/package.json
ui/yarn.lock

Support to import profiling file via relative URL. The reason to support this feature can be referred in this [PR](https://github.com/pingcap/tidb-dashboard/pull/1081)

chore: support import relative file URL

---

scripts/go.mod
scripts/go.sum
scripts/pd_version_matrix.go

The script can generate a version matrix table that can be shown in https://github.com/pingcap/tidb-dashboard/wiki/TiDB-Dashboard-×-PD-Version-Matrix

script: Add a script to generate version matrix

---

ui/go.mod

Update ui mod name to make PD can compile with tidb-dashboard.

update ui mod name

---

ui/go.mod

Reverts pingcap/tidb-dashboard#1115

Revert "update ui mod name"

---

pkg/apiserver/logsearch/pack.go
pkg/apiserver/model/common_models.go
pkg/apiserver/profiling/model.go
pkg/apiserver/profiling/pprof.go
pkg/apiserver/profiling/router.go
ui/lib/apps/ContinuousProfiling/pages/Detail.tsx
ui/lib/apps/InstanceProfiling/pages/Detail.tsx
ui/lib/apps/InstanceProfiling/translations/en.yaml
ui/lib/apps/InstanceProfiling/translations/zh.yaml
util/ziputil/zip_writer.go

What this PR did?
Address feedback for manual profiling:
1. update download file/folder name, eg. `cpu_pd_127.0.0.1:2379_1234567.proto`
2. add `README.md` to download zip folder.
3. add download text source file.

refine: address feedback

---

ui/lib/apps/InstanceProfiling/pages/Detail.tsx
ui/lib/apps/InstanceProfiling/translations/en.yaml
ui/lib/apps/InstanceProfiling/translations/zh.yaml

Fix the issue about distro res:

Refine distro and manual prof i18n

---

.github/workflows/test.yaml

Try to upload coverage report as a base report when master is updated.

tweak: run test & upload coverage report when master is updated

---

util/client/httpclient/response_test.go
util/client/pdclient/pd_api_highlevel_test.go
util/client/pdclient/pd_api_test.go
util/client/tidbclient/tidbproto/codec_test.go
util/csvutil/writer_test.go
util/distro/distro_test.go
util/gormutil/datatype/int_test.go
util/gormutil/datatype/int_withdb_test.go
util/gormutil/datatype/timestamp_test.go
util/gormutil/datatype/timestamp_withdb_test.go
util/gormutil/virtualview/schema_test.go
util/gormutil/virtualview/virtualview_test.go
util/netutil/parse_test.go
util/proxy/proxy_test.go
util/rest/fileswap/server_test.go
util/testutil/db.go
util/tlsutil/config_ext_test.go
util/topo/pdtopo/pd_test.go
util/topo/pdtopo/store_test.go
util/topo/provider_cached_test.go

For all test files in `/util`:
- Change `assert.x` to `require.x`
- Change `require.Nil(err)` to `require.NoError(err)`
- Change `require.NotNil(err)` to `require.Error(err)`

misc: update assert to require

---

.github/workflows/manual-create-pd-pr.yaml
.github/workflows/release.yaml
pkg/apiserver/diagnose/diagnose.go
release-version
ui/dashboardApp/layout/main/Sider/index.tsx
ui/lib/apps/ContinuousProfiling/pages/List.tsx
ui/lib/apps/SystemReport/pages/ReportGenerator.tsx
ui/lib/apps/SystemReport/translations/en.yaml
ui/lib/apps/SystemReport/translations/zh.yaml
ui/yarn.lock
util/client/httpclient/response_test.go
util/client/pdclient/pd_api_highlevel_test.go
util/client/pdclient/pd_api_test.go
util/client/tidbclient/tidbproto/codec_test.go
util/csvutil/writer_test.go
util/distro/distro_test.go
util/gormutil/datatype/int_test.go
util/gormutil/datatype/int_withdb_test.go
util/gormutil/datatype/timestamp_test.go
util/gormutil/datatype/timestamp_withdb_test.go
util/gormutil/virtualview/schema_test.go
util/gormutil/virtualview/virtualview_test.go
util/netutil/parse_test.go
util/proxy/proxy_test.go
util/rest/fileswap/server_test.go
util/testutil/db.go
util/tlsutil/config_ext_test.go
util/topo/pdtopo/pd_test.go
util/topo/pdtopo/store_test.go
util/topo/provider_cached_test.go

Release Note:
- Hide the `Cluster Diagnostic` app and rename the `System Report" app back to "Cluster Diagnostic"

Release v2022.01.12.1 [skip pd_pr]

---

release-version
ui/dashboardApp/index.ts
ui/lib/utils/appOptions.ts

Release v2022.01.17.1

---

ui/dashboardApp/layout/main/Sider/index.module.less
ui/lib/apps/DebugAPI/apilist/ApiList.module.less

Prev menu ✅:
Current menu ❌:
Prev debug api collapse ✅:
Current debug api collapse ❌:

Fix broken styles caused by antd update

---

.github/codecov.yml

This configuration removes the reach graph from the codecov comment.

ci: Add codecov.yml

---

ui/lib/apps/TopSQL/pages/List/ListChart.tsx
ui/lib/apps/TopSQL/translations/en.yaml
ui/lib/apps/TopSQL/translations/zh.yaml

chore: add cpu time axis title

---

ui/lib/utils/sqlFormatter/index.ts

Crashed workaround when format sql

---

.github/workflows/release.yaml
release-version
ui/lib/utils/sqlFormatter/index.ts

Release https://github.com/pingcap/tidb-dashboard/pull/1204

Release v2021.03.31

---

ui/lib/apps/ContinuousProfiling/pages/List.tsx

What did:
- Enable query history conprof results by changing a date even if the conprof feature is disabled

enable query when conprof is disabled

---

CONTRIBUTING.md
README.md

#sig-diagnosis Channel will be archived. Delete the related guide.

Update contact info.

---

ui/lib/apps/Overview/components/Metrics.tsx
ui/lib/apps/Overview/translations/en.yaml
ui/lib/apps/Overview/translations/zh.yaml
ui/lib/components/MetricChart/index.tsx

feat: show more metrics in overview

---

ui/cypress/integration/statement/01-list.spec.js
ui/cypress/integration/statement/02-detail.spec.js
ui/lib/apps/SearchLogs/components/SearchHeader.tsx
ui/lib/apps/Statement/pages/List/StatementSettingForm.tsx
ui/lib/apps/TopSQL/pages/List/SettingsForm.tsx
ui/lib/apps/TopSQL/translations/en.yaml
ui/lib/apps/TopSQL/translations/zh.yaml

Also fix https://github.com/pingcap/tidb-dashboard/issues/1243

feat: show info about data delay for Top SQL

---

ui/dashboardApp/layout/signin/index.tsx
ui/lib/apps/ContinuousProfiling/pages/List.tsx
ui/lib/apps/ContinuousProfiling/translations/en.yaml
ui/lib/apps/ContinuousProfiling/translations/zh.yaml
ui/lib/apps/InstanceProfiling/pages/List.tsx
ui/lib/apps/InstanceProfiling/translations/en.yaml
ui/lib/apps/InstanceProfiling/translations/zh.yaml
ui/lib/apps/KeyViz/components/KeyViz.tsx
ui/lib/apps/KeyViz/components/KeyVizToolbar.tsx
ui/lib/apps/KeyViz/translations/en.yaml
ui/lib/apps/KeyViz/translations/zh.yaml
ui/lib/apps/SlowQuery/pages/List/index.tsx
ui/lib/apps/SlowQuery/translations/en.yaml
ui/lib/apps/SlowQuery/translations/zh.yaml
ui/lib/apps/Statement/pages/List/index.tsx
ui/lib/apps/Statement/translations/en.yaml
ui/lib/apps/Statement/translations/zh.yaml
ui/lib/apps/TopSQL/pages/List/List.tsx
ui/lib/apps/TopSQL/translations/en.yaml
ui/lib/apps/TopSQL/translations/zh.yaml

This will bring users to our doc for various features.

feat: Add helper links and buttons

---

pkg/apiserver/utils/binary_plan.go

delete debug msg

---

pkg/apiserver/visualplan/service.go

fix api/visualplan/generate Content-Type

---

pkg/apiserver/statement/queries.go

fix: avoid query statement plan to make TiDB OOM

---

ui/packages/tidb-dashboard-for-clinic-cloud/package.json
ui/packages/tidb-dashboard-for-dbaas/package.json
ui/packages/tidb-dashboard-lib/package.json
ui/pnpm-lock.yaml

Related issue: https://github.com/YiniXu9506/metrics-chart/pull/10/files

fix: chart legend style

---

ui/packages/tidb-dashboard-for-clinic-cloud/package.json
ui/packages/tidb-dashboard-for-clinic-cloud/public/index.html
ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/SlowQuery/context.ts
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/SlowQuery/index.tsx
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/TopSQL/context.ts
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/TopSQL/index.tsx
ui/packages/tidb-dashboard-for-clinic-cloud/src/client/index.tsx
ui/packages/tidb-dashboard-for-clinic-cloud/src/dashboardApp/index.ts
ui/packages/tidb-dashboard-for-clinic-cloud/src/dashboardApp/main.tsx
ui/packages/tidb-dashboard-for-clinic-cloud/src/uilts/appOptions.ts
ui/packages/tidb-dashboard-for-dbaas/src/apps/TopSQL/context.ts
ui/packages/tidb-dashboard-for-op/.env.development
ui/packages/tidb-dashboard-for-op/src/apps/TopSQL/context.ts
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/context/index.ts
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/utils/useSlowQueryTableController.ts
ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/SlowQueryTab.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSQL/context/index.ts
ui/packages/tidb-dashboard-lib/src/apps/TopSQL/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/List.tsx

- Extend the start options, make it more configurable from outside, to support cloud ngm slow query and top sql app

refine clinic cloud variant

---

ui/packages/tidb-dashboard-for-clinic-cloud/package.json
ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/List.tsx
ui/packages/tidb-dashboard-lib/src/components/TimeRangeSelector/index.tsx
ui/pnpm-lock.yaml

The last 1min of top SQL data will always be generated in the process. We need to offset the time range.

tweak(topsql): time range offset

---

ui/packages/tidb-dashboard-for-clinic-cloud/package.json
ui/packages/tidb-dashboard-for-clinic-cloud/public/index.html
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Overview/context.ts
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Overview/index.tsx
ui/packages/tidb-dashboard-for-clinic-cloud/src/uilts/globalConfig.ts
ui/packages/tidb-dashboard-for-clinic-cloud/src/uilts/registry.ts
ui/packages/tidb-dashboard-for-op/src/apps/Overview/context.ts
ui/packages/tidb-dashboard-lib/src/apps/Overview/components/Metrics.tsx
ui/packages/tidb-dashboard-lib/src/apps/Overview/context/index.ts

Disable monitoring and search logs apps:

feat: support disable or enable apps

---

release-version
ui/packages/tidb-dashboard-for-clinic-cloud/package.json
ui/packages/tidb-dashboard-for-clinic-cloud/public/index.html
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Overview/context.ts
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Overview/index.tsx
ui/packages/tidb-dashboard-for-clinic-cloud/src/uilts/globalConfig.ts
ui/packages/tidb-dashboard-for-clinic-cloud/src/uilts/registry.ts
ui/packages/tidb-dashboard-for-op/src/apps/Overview/context.ts
ui/packages/tidb-dashboard-lib/src/apps/Overview/components/Metrics.tsx
ui/packages/tidb-dashboard-lib/src/apps/Overview/context/index.ts

Reverts pingcap/tidb-dashboard#1454
Wrong version number

Revert "Release TiDB Dashboard v6.5.0 [skip pd_pr]" [skip pd_pr]

---

pkg/apiserver/logsearch/task.go

ref: #1478
see: https://github.com/tikv/client-go/pull/88
Signed-off-by: mornyx <mornyx.z@gmail.com>

grpc: change max receive size to maxInt64 - 1

---

release-version

After closing the telemetry by PR #1482 , we need to patch back to TiDB Dashboard 6.5.0

Release v6.5.1

---

ui/packages/tidb-dashboard-for-dbaas/package.json
ui/packages/tidb-dashboard-for-dbaas/public/index.html
ui/packages/tidb-dashboard-for-dbaas/src/apps/SQLAdvisor/context.ts
ui/packages/tidb-dashboard-lib/src/apps/SQLAdvisor/component/IndexInsightList.tsx
ui/packages/tidb-dashboard-lib/src/apps/SQLAdvisor/component/IndexInsightListWithRegister.tsx
ui/packages/tidb-dashboard-lib/src/apps/SQLAdvisor/component/IndexInsightTable.tsx
ui/packages/tidb-dashboard-lib/src/apps/SQLAdvisor/context/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/SQLAdvisor/pages/Detail/index.tsx

- add cancelRunningTask button
- move `Deactivate` button to Setting Drawer.
- Pop up notice when `Check Up` button clicked.
- Refine some description.

chore: refine sql advisor

---

ui/packages/tidb-dashboard-for-clinic-cloud/.env.development
ui/packages/tidb-dashboard-for-clinic-cloud/builder.js
ui/packages/tidb-dashboard-for-clinic-cloud/package.json
ui/packages/tidb-dashboard-for-clinic-cloud/public/o11y.html
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Statement/context.ts
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Statement/index.tsx
ui/packages/tidb-dashboard-for-clinic-cloud/src/dashboardApp/main.tsx
ui/packages/tidb-dashboard-for-clinic-cloud/src/utils/globalConfig.ts
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/context/index.ts
ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/zh.yaml
ui/packages/tidb-dashboard-lib/src/apps/Statement/utils/useStatementTableController.ts
ui/packages/tidb-dashboard-lib/src/components/MultiSelect/index.tsx

1. Can hide databases filters
2. Can hide config
3. Can hide actual time range message
4. Can limit the time range
5. Sort stmt types
6. Support hide the page load progress bar
7. Fix statement navigation back issue that lost the selected time range info

feat: adjust statement work for serverless clusters

---

dockerfiles/alpine316.Dockerfile
dockerfiles/centos7.Dockerfile

fix failed ci:
https://github.com/pingcap/tidb-dashboard/actions/runs/4552676273/jobs/8048317108?pr=1506

use fixed pnpm version to build image

---

ui/packages/tidb-dashboard-lib/src/apps/ResourceManager/uilts/metricQueries.ts

update resource manager cpu for instance rather than sum

resource_manager: update resource manager cpu for instance

---

ui/packages/tidb-dashboard-lib/src/apps/ResourceManager/components/EstimateCapacity.tsx

resource_manager: fix burstable

---

ui/packages/tidb-dashboard-lib/src/apps/ResourceManager/components/Configuration.tsx

to resolve the issue: https://asktug.com/t/topic/1008382

chore: enlarge resource group column width to show long name

---

ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
ui/packages/tidb-dashboard-for-clinic-cloud/src/client/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Detail/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/index.tsx
ui/packages/tidb-dashboard-lib/src/utils/openLink.ts

This PR refines some experience when using tidb-dashboard in clinic platform:
- Jump back to clinic homepage is meet 401
- Make go back for slow query detail page and statement detail page more elegant
- Fix url when opening slow query detail page in the new tab

chore: refine for clinic

---

ui/packages/tidb-dashboard-lib/src/apps/Monitoring/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/Monitoring/translations/zh.yaml
ui/packages/tidb-dashboard-lib/src/apps/Overview/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/Overview/translations/zh.yaml

Signed-off-by: mornyx <mornyx.z@gmail.com>

chore: fix prometheus typo

---

ui/packages/tidb-dashboard-lib/src/components/BinaryPlanTable/index.module.less
ui/packages/tidb-dashboard-lib/src/components/BinaryPlanTable/index.tsx

https://github.com/pingcap/tidb-dashboard/assets/1284531/844bacb6-b87e-4328-9edf-11dd0970f677

chore(binary-plan): show eye icon to hide column when hover

---

pkg/apiserver/debugapi/apis.go
pkg/apiserver/debugapi/endpoint/models.go
ui/packages/tidb-dashboard-for-op/src/utils/distro/strings_res.json
ui/packages/tidb-dashboard-lib/src/apps/DebugAPI/apilist/ApiForm.tsx
ui/packages/tidb-dashboard-lib/src/apps/DebugAPI/translations/en.yaml

This PR supports to download the ddl history by pagination.

feat(debug-api): support pagination for ddl history

---

ui/packages/tidb-dashboard-for-clinic-cloud/public/index.html
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Overview/context.ts
ui/packages/tidb-dashboard-for-op/src/apps/Overview/context.ts
ui/packages/tidb-dashboard-lib/src/apps/Overview/components/Metrics.tsx
ui/packages/tidb-dashboard-lib/src/apps/Overview/context/index.ts
ui/packages/tidb-dashboard-lib/src/apps/Overview/index.tsx

chore: hide resource manager and overview monitoring for clinic cloud

---

ui/packages/tidb-dashboard-lib/src/apps/UserProfile/components/Form.SSO.tsx

According the user request in https://github.com/pingcap/tidb-dashboard/pull/1599#discussion_r1356141654 , we support to customize the OIDC scopes for sso login.

chore(sso): support customize OIDC scopes

---

Makefile
pkg/utils/version/fips.go

build:
```
ENABLE_FIPS=1 make server
```
check
```
go tool nm bin/tidb-dashboard | grep boring
```

*: add fips build support

---

Makefile
pkg/utils/version/fips.go

Cherry-pick https://github.com/pingcap/tidb-dashboard/pull/1612

*: add fips build support (#1612)

---

cmd/tidb-dashboard/main.go
pkg/apiserver/apiserver.go
pkg/apiserver/clusterinfo/host.go
pkg/apiserver/clusterinfo/service.go
pkg/apiserver/clusterinfo/statistics.go
pkg/apiserver/debugapi/endpoint/payload.go
pkg/apiserver/model/common_models.go
pkg/apiserver/profiling/fetcher.go
pkg/apiserver/profiling/jeprof.in
pkg/apiserver/profiling/pprof.go
pkg/config/config.go
pkg/tikv/client.go
pkg/utils/topology/models.go
pkg/utils/topology/ticdc.go
release-version
ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/context/index.ts
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
util/client/ticdcclient/status_client.go
util/topo/model.go

- https://github.com/pingcap/tidb-dashboard/pull/1614
- https://github.com/pingcap/tidb-dashboard/pull/1621
- https://github.com/pingcap/tidb-dashboard/pull/1622
- https://github.com/pingcap/tidb-dashboard/pull/1624

Release 20231218

---

pkg/utils/topology/ticdc.go

ref https://github.com/pingcap/tiflow/issues/10375

add more deploy info to ticdc

---

ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/List.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/ListTable.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSQL/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/TopSQL/translations/zh.yaml

This PR adds the action to search in sql statements for top sql record in the table.

feat(topsql): add action to search in sql statements

---

ui/packages/clinic-client/src/client/api/api.ts
ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
ui/packages/tidb-dashboard-lib/src/apps/TopSQL/context/index.ts
ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/ListTable.tsx

chore(topsql): hide action in table for clinic

---

ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/TopSlowQuery/context-provider.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/context.ts
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/CountChart.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.module.less
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/ListTable.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/helpers.ts
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/url-state.ts

What this PR did:
1. change line chart to bar chart
2. add order by filter
3. add extra style for the table sorted column header to make it more explicit

chore(top_slowuqery): address feedback

---

ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/TopSlowQuery/context-provider.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/context.ts
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/CountChart.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/helpers.ts
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/url-state.ts

feat(top_slowquery): support select time range on the chart

---

ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/SlowQuery/context.ts
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/DownloadDBFileModal.tsx

- Fix slowquery log download api.
- Add reminder for UTC-0
- Add time range preview for slow log to download.

fix(slow_query): fix download slowlog api, add range preview and timezone reminder

---

ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/TopSlowQuery/context-provider.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/utils/list-url-state.ts
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/context.ts
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.module.less
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/ListTable.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/helpers.ts
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/uilts/url-state.ts

feat(top_slowquery): support multiple db and statement type filter

---

ui/packages/tidb-dashboard-lib/package.json
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/zh.yaml
ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/ListDetail/ListDetailTable.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/ListTable.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/CountChart.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/List.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSlowQuery/pages/ListTable.tsx
ui/pnpm-lock.yaml

feat: support download table to csv for top sql, slow query

---

ui/packages/tidb-dashboard-for-op/src/apps/Monitoring/metricsQueries.ts

monitoring: fix the tps metric

---

ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Monitoring/metricsQueries.ts
ui/packages/tidb-dashboard-for-op/src/apps/Monitoring/metricsQueries.ts

monitoring: fix tps for clinic

---

ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/List.tsx

TopSQL can be configured to display the top n results. before always is 5, some cases cannot cover.

ui: TopSQL can be configured to display the top n results

---

ui/packages/tidb-dashboard-lib/src/components/DateTime/calendarPlugin.ts

close #1698 
When comparing the week, the old algorithm doesn't consider the year of the date. for example: `2024-06-21` (Friday, the 25th week of 2024) and `2023-06-25` (Sunday, the 25th week of 2023). The old algorithm recognizes these 2 dates are in the same week, it's obvious not correct!

fix: fix calendar algorithm

---

pkg/apiserver/clusterinfo/hostinfo/cluster_config.go

dashboard/api/host/all: add ticdc instance information to host/all api

---

scripts/create_release_tag.js

cherry-pick #1720 #1721 from master to release-8.1 branch

chore: refine make tag
