.github/workflows/release-ui-assets.yaml
Makefile
README.md
cmd/tidb-dashboard/main.go
ui/.github_release_version
ui/package.json
ui/src/utils/client/index.js

This PR adds `/dashboard` prefix to both UI and API endpoint, to make it easy to be integrated with PD.
Additionally, looks like `yarn install` without specifying private token over an installed workspace is fine, so this PR also removes the `SKIP_YARN_INSTALL` flag.
Note: A swagger rebuild is required after this PR.

Add /dashboard prefix

---

.github/workflows/release-ui-assets.yaml
cmd/tidb-dashboard/main.go
pkg/apiserver/apiserver.go
pkg/apiserver/foo/foo.go
pkg/apiserver/info/info.go
pkg/config/config.go
scripts/embed_ui_assets.sh

Support specifying some CLI flags like listen host, listen port, data dir and pd address.
PD address is also available via `/api/info` so that front-end can connect to PD directly.

Add support for CLI flags

---

README.md
go.mod
go.sum
pkg/apiserver/apiserver.go
pkg/apiserver/info/info.go
ui/.github_release_version
ui/src/apps/demo/index.js
ui/src/apps/keyvis/RootComponent.less
ui/src/apps/keyvis/RootComponent.tsx
ui/src/apps/keyvis/ToolBar.tsx
ui/src/apps/keyvis/api.ts
ui/src/apps/keyvis/heatmap/chart.ts
ui/src/apps/keyvis/index.js
ui/src/index.js
ui/src/layout/RootComponent.js

Hide some menu items in non dev mode

---

ui/public/index.html
ui/src/utils/i18n.js

Previously when browser is in simplified chinese language, the detected language code is `zh-CN`. However our language code is `zh_CN`, which result in translation keys not correctly translated.
Now fallback language has been added, and language code is changed to `zh-CN`.

Fix language fallback and auto detection

---

pkg/apiserver/clusterinfo/service.go
pkg/utils/clusterinfo/fetcher.go

Previous pr uses `Url.Host` to get ip, and there was a problem that it returns ip:port. This pr fix that problem.
Signed-off-by: mapleFU <1506118561@qq.com>

clusterinfo: Fix ip and port error

---

pkg/apiserver/diagnose/diagnose.go
pkg/apiserver/diagnose/report.go
pkg/apiserver/diagnose/report_test.go

before: the error happend in generating report would stop the generating process.
this pr: these error would be imported to a table.
change a table's return err for test:

Add error table to make err happend in report's generating process imported to a table

---

ui/src/apps/clusterInfo/components/ClusterInfoTable.js

Previous pr just count TiDB numbers in all kinds of nodes, this pr changes it to the right data.
Signed-off-by: mapleFU <1506118561@qq.com>

clusterinfo: Fix error usage of node count in ClusterInfoTable

---

.github/workflows/release-ui-assets.yaml
README.md
ui/.yarnrc
ui/yarn.lock

Because I published the [grafana-value-formats](https://www.npmjs.com/package/@baurine/grafana-value-formats) lib to npm registry as well, so now we can remove the setting to install from GitHub Packages.

build: remove installing npm packages from GitHub Packages

---

pkg/apiserver/diagnose/templates.go

This PR is to fix the browser reported "Uncaught SyntaxError: missing ) after argument list" error, this error makes the "expand" button doesn't work in the diagnosis report page.

diagnosis: fix miss bracket syntax error

---

CONTRIBUTING.md
cmd/tidb-dashboard/main.go
go.mod

UCP #138 
Replace the package `flag` with `pflag`
Hide help information for debug parameters, including `keyvis-file-start` and `keyvis-file-end`
New feature 
Have run command `make run` successfully
No

cmd/tidb-dashboard: replace flag with pflag

---

pkg/apiserver/diagnose/report.go
pkg/apiserver/diagnose/report_test.go

cluster：
before：
this pr：
2 cores：
4 cores：
6 cores：
8 cores：
15 cores：
We can see that over 6 cores it would not get better performance. It due to some siggle table cost too much time that makes the whole time equal it’s time. So I set the cores not beyond 8 cores.

Sql diagnosis: make GetReportTables perform concurrently 

---

scripts/lint.sh

because golangci-lint 1.23.3 does NOT play well with go 1.14
**Related issue** 
https://github.com/pingcap-incubator/tidb-dashboard/issues/172

build: upgrade golangci-lint from 1.23.3 to 1.23.8

---

pkg/apiserver/apiserver.go
pkg/keyvisual/service.go

The `Service.Stop` function has been blocked because `ctx` was not canceled.
This PR fixes this issue.

service: cancel the internal context when stopped

---

cmd/tidb-dashboard/main.go
pkg/apiserver/apiserver.go

`apiserver` provides `Handler` directly, which is more convenient for integration in PD.

*: add apiserver.Handler

---

pkg/keyvisual/decorator/tidb.go
ui/packages/keyvis/src/heatmap/chart.ts

UCP #247 
Add DB Name in the function `Label` of decorator
Change some parameters in ui/packages/keyvis/src/heatmap/chart.ts
Improvement
Run the following commands in order：
`make ui`
`UI=1 SWAGGER=1 make server`
`make run`
As a result, open the front end and display `DB Name` correctly
No

keyvis: support to display DB Name

---

pkg/apiserver/diagnose/report.go

Change `metric-storage` check.
After https://github.com/pingcap/tidb/pull/15304, Setting the PD `metric-storage` config value is not necessary anymore.

diagnose: fix metric-storage check

---

pkg/tidb/conn.go

UCP #224
If `TIDB_OVERRIDE_ENDPOINT` ENV is set, the server would read it to connect to the tidb-server. Otherwise it would work as the previous.

Add Tidb Endpoint

---

ui/packages/statement/package.json

This make the bundle size reduce from 1.1M back to 39KB.

add @ant-design/icons dependency for statement

---

.github/workflows/e2e-test.yaml
ui/packages/statement/src/components/StatementSummaryTable.tsx

- only import sql syntax highlight instead of importing all languages to reduce bundle size
This can help reduce the highlight.js bundle size from ~900KB to ~30KB.
Ref: https://www.npmjs.com/package/react-syntax-highlighter#light-build

ui: reduce bundle size

---

pkg/apiserver/apiserver.go

In order to use different `stopHandlers` for `apiserver` and `uiserver` in PD.

apiserver: NewStatusAwareHandler can use custom stopHandler

---

pkg/apiserver/diagnose/templates/index.gohtml
pkg/apiserver/diagnose/templates/navigator.gohtml
pkg/apiserver/diagnose/templates/table.gohtml

UCP #200
Add a left navigator for diagnose report.
- Add a `id` property for `h3` HTML tag as anchor. It takes value from `TableDef.Title`.
- Add a new template file `navigator.gohtml`.
- Some CSS in `index.gohtml`
New feature.
Manually tested.
Preview:
HTML file: https://paste.ubuntu.com/p/ksXCmTjHgr/
No.
#200

feat(diagnose): add a sample left navigator for diagnose report

---

ui/package.json
ui/packages/statement/package.json
ui/packages/statement/src/RootComponent.tsx
ui/src/apps/diagnose/RootComponent.js
ui/src/apps/diagnose/components/DiagnoseGenerator.tsx
ui/src/apps/instanceProfiling/RootComponent.js
ui/src/apps/instanceProfiling/pages/List.js
ui/src/apps/searchLogs/RootComponent.js
ui/src/apps/searchLogs/components/SearchHeader.tsx
ui/yarn.lock

UCP https://github.com/pingcap-incubator/tidb-dashboard/issues/249
Update to react-router6

update to react-router 6

---

ui/src/apps/clusterInfo/pages/List.js

cluster_info: fix empty start_timestamp in cluster info page

---

ui/packages/statement/src/RootComponent.tsx

After https://github.com/pingcap-incubator/tidb-dashboard/pull/301, entering `/statement` will be redirected to `/statement/overview` after mounted but this does not affect the later routing to `/statement`. This PR fixes this behavior.

Use /statement instead of /statement/overview

---

ui/diagnoseReportApp/components/DiagnosisReport.tsx
ui/diagnoseReportApp/components/DiagnosisTable.tsx
ui/diagnoseReportApp/index.css
ui/diagnoseReportApp/index.js
ui/diagnoseReportApp/translations/en.yaml
ui/diagnoseReportApp/translations/zh-CN.yaml
ui/diagnoseReportApp/types.ts

What did:
- Add navigation menus for all report tables
- Sticky the nav menu
- Sticky the tables  header
- Remove duplicated category
The design is coarse and ugly, can be refined later.
@crazycs520

Add navigation menu for diagnosis reports

---

pkg/apiserver/slowquery/queries.go
pkg/apiserver/slowquery/service.go
ui/lib/apps/SlowQuery/components/Detail.tsx
ui/lib/apps/SlowQuery/components/List.tsx
ui/lib/apps/SlowQuery/components/TimeRangeSelector.tsx
ui/lib/apps/SlowQuery/utils/useColumn.tsx

slow_query: improvement slow query page

---

pkg/apiserver/slowquery/queries.go
ui/lib/apps/SlowQuery/components/List.tsx

slow_query: fix bugs in slow query page

---

ui/lib/apps/ClusterInfo/components/HostTable.js
ui/lib/apps/ClusterInfo/components/InstanceTable.js
ui/lib/apps/ClusterInfo/pages/List.js

cluster_info: fix UI bug in cluster_info

---

ui/lib/apps/Statement/pages/List/index.tsx
ui/lib/components/CardTableV2/index.tsx

resolve #444 
What did:
- Use ShimmeredDetailsList to represent loading status for not re-mount the DatailsList when reloading data
- Keep changed columns width when reloading data in the current page
- Show the existed old data when reloading
Failed to do:
- Persist the width of the columns.
According to the issue https://github.com/microsoft/fluentui/issues/9287 , this feature isn't supported by DatailsList.
Do you guys have any idea?

Remember columns width

---

pkg/apiserver/logsearch/task.go

UCP #203 
Support Case Insensitive Log Searching
By modifying regexp patterns with an `(?i)` ignore-case flag before sending `SearchLogRequest` to gRPC service.

Support case-insensitive log searching

---

ui/lib/apps/ClusterInfo/components/HostTable.js
ui/lib/apps/ClusterInfo/components/InstanceTable.js
ui/lib/apps/Diagnose/components/DiagnoseHistory.tsx
ui/lib/apps/InstanceProfiling/pages/List.js
ui/lib/apps/SlowQuery/components/SlowQueriesTable.tsx
ui/lib/apps/SlowQuery/pages/List/index.tsx
ui/lib/apps/SlowQuery/translations/en.yaml
ui/lib/apps/SlowQuery/translations/zh-CN.yaml
ui/lib/apps/SlowQuery/utils/useColumn.tsx
ui/lib/apps/Statement/components/StatementsTable.tsx
ui/lib/apps/Statement/pages/List/index.tsx
ui/lib/apps/Statement/utils/useColumn.tsx
ui/lib/apps/Statement/utils/useStatement.ts
ui/lib/components/CardTableV2/index.tsx

resolve #447 
What did:
- Revert doesn't work code for persisting columns width
- Move all logic about sorting down to CardTableV2 to reduce duplicated logic
- Fix the wrong usage for hooks so now we can cache the tableColumns
- Fix the TimeRangeSelector doesn't work as expected

Refine order and desc

---

ui/lib/apps/SlowQuery/components/SlowQueriesTable.tsx
ui/lib/apps/Statement/components/StatementsTable.tsx

Hi @breeswish , I forgot the slow queries may have the same digest, using `getKey={row => row?.digest}` will cause duplicate keys for slow query table, so I add more fields to avoid this. Although `row?.digest` works fine for statement table, I add more as well just in case.
Or we can wait for your PR which mentioned in https://github.com/pingcap-incubator/tidb-dashboard/pull/454#issuecomment-625242923 if it relates to this.

avoid duplicate keys for table rows

---

ui/lib/apps/SearchLogs/LogSearchingDetail.tsx

Fix the bug when all log search tasks finished, polling task status should stop.

log_search: stop polling tasks status when all tasks finished

---

ui/lib/apps/ClusterInfo/components/HostTable.tsx
ui/lib/apps/ClusterInfo/components/InstanceTable.tsx

What did:
- Refine InstanceTable, add tooltip for version/deploy_path/git_hash columns, add dummyColumn
- Refine HostTable, add tooltip for disk column
Before:
After:

Refine instance host tables

---

ui/lib/apps/SlowQuery/pages/List/index.tsx
ui/lib/apps/Statement/pages/List/index.tsx
ui/lib/components/Card/index.module.less
ui/lib/components/Card/index.tsx
ui/lib/components/CardTableV2/index.tsx

fix #462 
What did:
- Fix the bug that sticky table header can't scroll with the body in the horizontal direction
The original situation:
According to the issue: https://github.com/microsoft/fluentui/issues/7742 , the easiest way is to just set `constrainMode={ConstrainMode.unconstrained}` for DetailsList. This makes the sticky table header scrolls with its body but makes the sticky toolbar scrolls as well (same as the official demo), I don't think it is expected.
So I only wrap the table instead of the root container by `<ScrollablePane>`.
But the margin collapse doesn't work anymore, it makes the sticky table header jumping when it switches between sticky or not.
Adding another new props `noMarginTop` to remove the additional margin-top, maybe not very elegant, doesn't know whether it …

Fix sticky table header can't scroll with its body in horizontal direction

---

pkg/apiserver/profiling/router.go
ui/lib/apps/InstanceProfiling/pages/Detail.tsx
ui/lib/apps/InstanceProfiling/translations/en.yaml
ui/lib/apps/InstanceProfiling/translations/zh-CN.yaml

What did:
- Support view single profiling online
- Support download single profiling file
- Unify the get action token handler
Screenshots:

profiling: support view and download a single profiling

---

ui/lib/apps/Diagnose/components/DiagnoseGenerator.tsx
ui/lib/apps/Diagnose/components/DiagnoseHistory.tsx
ui/lib/apps/InstanceProfiling/pages/List.tsx
ui/lib/apps/SearchLogs/components/SearchHistory.tsx

What did:
- Fix layout for dianosis history / log search history / profiling history tables when in small screen.
Before:
After:

ui: Fix others table layout when small screen

---

pkg/apiserver/logsearch/task.go
ui/lib/apps/SearchLogs/components/SearchProgress.tsx

UCP https://github.com/pingcap-incubator/tidb-dashboard/issues/507
Fix #492
Also, disable the tree node in log searching progress sidebar if the related task fails or has no searching results

ignore empty log searching results

---

pkg/uiserver/uiserver.go

Add Gzip Support for uiserver

---

ui/lib/apps/SearchLogs/pages/LogSearchHistory.tsx
ui/lib/apps/SearchLogs/translations/en.yaml
ui/lib/apps/SearchLogs/translations/zh-CN.yaml
ui/lib/apps/SlowQuery/pages/Detail/DetailTabCopr.tsx
ui/lib/apps/SlowQuery/pages/Detail/DetailTabTxn.tsx
ui/lib/apps/Statement/pages/Detail/PlanDetailTabBasic.tsx
ui/lib/apps/Statement/pages/Detail/PlanDetailTabCopr.tsx
ui/lib/apps/Statement/pages/Detail/PlanDetailTabTxn.tsx
ui/lib/components/ShortValueWithTooltip/index.tsx
ui/lib/components/index.ts

close #513, #501 
What did:
- Show confirm before deleting log search histories
- Show tooltip for short values in the statement / slow query detail page tables
Screenshots:

Some ui refinements

---

ui/lib/apps/Overview/components/Instances.tsx
ui/lib/apps/Overview/components/Styles.module.less

This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.

ui: remove deprecated <big> element

---

cmd/tidb-dashboard/main.go
pkg/apiserver/apiserver.go
pkg/apiserver/logsearch/scheduler.go
pkg/apiserver/logsearch/service.go
pkg/apiserver/metrics/metrics.go
pkg/config/dynamic_config_manager.go
pkg/keyvisual/decorator/tidb.go
pkg/keyvisual/decorator/tidb_requests.go
pkg/keyvisual/input/api.go
pkg/keyvisual/input/file.go
pkg/keyvisual/input/input.go
pkg/keyvisual/region/interface.go
pkg/keyvisual/service.go
pkg/keyvisual/storage/stat.go
pkg/pd/http_client.go
pkg/pd/pd.go
pkg/tidb/conn.go
pkg/tidb/forwarder.go
pkg/tidb/tidb.go
pkg/utils/topology/pd.go
pkg/utils/topology/store.go

* *: rename some `ctx` to `lifecycleCtx`
* pd: pd http client will automatically complete the `/pd/api/v1` prefix
* tidb: support `SendGetRequest` like `pd.Client` to handle `ctx` automatically
* keyviz: 
* use pd and tidb client to send request
* refactor `region.DataProvider`, remove logic related to pd
**Note**: Need to update PD code.

*: tidb forwarder support http request and refactor keyviz

---

ui/lib/antd.override.less

fix Descriptions.Item has different look between Chrome and Safari

---

ui/lib/utils/telemetry.ts

close #655
If there are remaining data were not sent out last time, mixpanel will send them out immediately when initiating. So we should assign the customized API host when initiating, else mixpanel will send the remaining data to the default API host before changing it.
Before:
After:

telemetry: assign the customized API host when initiating the mixpanel

---

CONTRIBUTING.md
ui/src/setupProxy.js
ui/tests/config-portal-test.html
ui/tests/e2e/test_config.ts

Update the related docs and code after changing the default frontend port to 3001.
Related issue and PR: #666 #667

update the related docs and code after changing the fe port

---

CONTRIBUTING.md

When following the contribute docs to set the development workspace, i found the step of environment variable declare is missed and get the warning that `Command 'tiup' not found`.
I update the contribute docs and add the required step. 
No code change 
No impact

Docs : Add environment variable declare step in  Contributing

---

cmd/tidb-dashboard/main.go
pkg/apiserver/info/info.go
pkg/config/config.go
ui/lib/utils/telemetry.ts

* config: rename `disable_telemetry` to `enable_telemetry`
* ui: rename `disable_telemetry` to `enable_telemetry`
* info: remove the useless `pd_end_point` that should not be returned
partially solve #670

Rename disable_telemetry to enable_telemetry

---

pkg/http/http.go
pkg/keyvisual/decorator/decorator.go
pkg/keyvisual/matrix/axis.go
pkg/keyvisual/matrix/plane.go

keyviz: support to merge cold logical range

---

pkg/apiserver/statement/queries.go

To fix https://github.com/pingcap-incubator/tidb-dashboard/issues/582
Follow suggestion, replaced `UNIX_TIMESTAMP` with `FROM_UNIXTIME` in statement query where condition.

Backend: replace UNIX_TIMESTAMP with FROM_UNIXTIME in statement query

---

.github/workflows/e2e-test.yaml
release-version
ui/tests/e2e/search_log.test.ts

- Add an extra step to debug TiUP
- Search logs by keyword "welcome" to reduce the result size
After this change, the "Test / UI" job has success 5 times continuously. (Although I don't know why the big result size causes the job not stable)

Make e2e test not often fail

---

pkg/apiserver/statement/models.go
pkg/apiserver/statement/queries.go
ui/lib/apps/Statement/pages/Detail/index.tsx
ui/lib/apps/Statement/pages/List/index.tsx
ui/lib/apps/Statement/translations/en.yaml
ui/lib/apps/Statement/translations/zh.yaml
ui/lib/apps/Statement/utils/tableColumns.tsx

statement: Display number of plans in the list

---

pkg/apiserver/diagnose/diagnose.go
release-version
ui/lib/apps/Diagnose/pages/DiagnoseGenerator.tsx
ui/lib/apps/Diagnose/translations/en.yaml
ui/lib/apps/Diagnose/translations/zh.yaml

feature: Generate metrics relationship graph

Release v2020.09.21.1

---

ui/dashboardApp/layout/main/Sider/Banner.tsx
ui/dashboardApp/layout/main/Sider/index.module.less
ui/dashboardApp/layout/main/Sider/index.tsx
ui/dashboardApp/layout/main/index.module.less
ui/dashboardApp/layout/main/index.tsx

- make the animation of width changing smooth
- improve performance
expanding and collapsing the sidebar for one time in six seconds, the left one is controlled by JS and the right one is controlled by CSS

ui: improve the expansion and collapse of sider menu

---

ui/dashboardApp/index.ts

The stack trace is useless without source map, and also it is very hard to understand what error is going on without the error message.
(Using `''+e` instead of `e.message` to be compatible with non-Exception errors)

ui: display error message instead of stack trace on connect failure

---

pkg/keyvisual/matrix/axis.go
pkg/keyvisual/matrix/axis_test.go

In the `keyvisual.matrix` package, `chunk.Reduce(keys{"", ""})` will cause a panic.
* The original code preset `keys[i] != keys[i+1]`, only `keys{"", ""}` does not match. So make a special judgment on it.
* Add unittests.

keyviz: fix panic in matrix package

---

ui/lib/apps/SlowQuery/pages/Detail/index.tsx
ui/lib/apps/Statement/pages/Detail/PlanDetail.tsx
ui/lib/apps/Statement/pages/Detail/index.tsx

memorize whether expand full text in statements page and slow queries page.
close #747

ui: memorize whether expand full text in detail pages

---

ui/lib/apps/SlowQuery/utils/tableColumns.tsx
ui/lib/apps/SlowQuery/utils/useSlowQueryTableController.ts
ui/lib/apps/Statement/utils/tableColumns.tsx
ui/lib/apps/Statement/utils/useStatementTableController.ts
ui/lib/utils/tableColumnFactory.tsx

calculating selectedFields no longer need tableColumns
close #764

ui: break loop dependencies

---

ui/gulpfile.esm.js
ui/public/checkBrowser.js
ui/public/compat.js
ui/public/diagnoseReport.html
ui/public/index.html

---
close #770 
when testing the related issue on the low version of the Firefox, we found that alert from checkBrowser.js can't appear for the experimental API checkBrowser.js uses is not supported by these low version browsers.

ui: remove experimental API in checkBrowser.js

---

pkg/apiserver/slowquery/queries.go
pkg/apiserver/statement/models.go
ui/lib/apps/SlowQuery/pages/Detail/DetailTabBasic.tsx
ui/lib/apps/SlowQuery/translations/en.yaml
ui/lib/apps/SlowQuery/translations/zh.yaml
ui/lib/apps/SlowQuery/utils/tableColumns.tsx
ui/lib/apps/Statement/pages/Detail/PlanDetailTabBasic.tsx
ui/lib/apps/Statement/translations/en.yaml
ui/lib/apps/Statement/translations/zh.yaml
ui/lib/apps/Statement/utils/tableColumns.tsx

close #739 
Screenshots:
These new columns seem to only exist in the new TiDB version, but I don't think we need to handle the compatibility problem before the dashboard has a standalone deployment mode, right?

ui: show disk usage information for statement and slow query

---

go.mod
go.sum
pkg/apiserver/statement/models.go
pkg/apiserver/statement/queries.go
pkg/apiserver/statement/statement.go
ui/lib/apps/SearchLogs/components/SearchProgress.tsx
ui/lib/apps/Statement/pages/List/index.tsx
ui/lib/apps/Statement/translations/en.yaml
ui/lib/apps/Statement/translations/zh.yaml
ui/lib/apps/Statement/utils/useStatementTableController.ts

close #565 
What did:
- Export the queried statements result as .csv format file
Screenshots:
(mocked time delays)

export statements

---

pkg/apiserver/slowquery/queries.go
pkg/apiserver/slowquery/service.go
ui/lib/apps/SlowQuery/pages/Detail/index.tsx
ui/lib/apps/SlowQuery/utils/useSlowQueryTableController.ts

Use string primitive type for some uint64 fields

---

ui/lib/client/index.tsx
ui/lib/components/TextWithInfo/index.tsx

Reason: 
`i18next.t()` method will truncate some contents and convert colons to dots if the content contains colons.
Example: 
```js
console.log(
i18next.t('Test: error message with colons: colons will become dots') // error message with colons. colons will become dots
)
```
We also refine the logic a bit. If errCode hasn't a translation, we show the original detail error message instead.

ui: fix the error message doesn't show correct

---

pkg/apiserver/statement/models.go

When query statement detail, dashboard uses to use `ROUND` function to query, but it may cause the flowing error:
This is caused by the `ROUND` function result is `float64`, not `int`, here is an example.
```sql
test> create table t (a int, b double);
Query OK, 0 rows affected
Time: 0.044s
test> insert into t values (62695, 2240325.4838709678),(6, 0.0);
Query OK, 2 rows affected
Time: 0.042s
test> select round(sum(a*b)/sum(a)) as avg from t;
+-----------+
| avg       |
+-----------+
| 2240111.0 |
+-----------+
```
This PR use `CAST( ... AS SIGNED)` function instead of `ROUND` when query statement detail.

*: fix query statement detail error cause by round

---

ui/lib/apps/SlowQuery/pages/Detail/index.tsx
ui/lib/apps/Statement/pages/Detail/PlanDetail.tsx
ui/lib/apps/Statement/pages/Detail/index.tsx
ui/lib/components/CopyLink/index.tsx

ui: copy original content instead of formatted content for CopyLink

---

ui/lib/apps/ClusterInfo/components/StoreLocation.tsx
ui/lib/apps/ClusterInfo/components/StoreLocationTree/index.tsx
ui/lib/apps/ClusterInfo/translations/en.yaml
ui/lib/apps/ClusterInfo/translations/zh.yaml

also add i18n for tooltip
close #801

add min height of topology canvas

---

ui/dashboardApp/layout/main/Sider/Banner.tsx
ui/dashboardApp/layout/main/Sider/index.module.less
ui/dashboardApp/layout/main/Sider/index.tsx
ui/dashboardApp/layout/main/index.module.less
ui/dashboardApp/layout/main/index.tsx

close #800 
This reverts commit 47a9db5470e5b660f31f6653ebb4cc337a184e0b.

Revert "ui: improve the expansion and collapse of sider menu (#767)"

---

etc/manualTestEnv/_shared/Vagrantfile.partial.pubKey.rb
etc/manualTestEnv/complexCase1/README.md
etc/manualTestEnv/complexCase1/Vagrantfile
etc/manualTestEnv/complexCase1/topology.yaml
etc/manualTestEnv/multiReplica/README.md
etc/manualTestEnv/singleHost/README.md
etc/manualTestEnv/singleHostMultiDisk/README.md
pkg/apiserver/clusterinfo/host.go
pkg/apiserver/clusterinfo/hostinfo/cluster_config.go
pkg/apiserver/clusterinfo/hostinfo/cluster_hardware.go
pkg/apiserver/clusterinfo/hostinfo/cluster_load.go
pkg/apiserver/clusterinfo/hostinfo/hostinfo.go
pkg/apiserver/clusterinfo/service.go
pkg/apiserver/clusterinfo/statistics.go
pkg/utils/host/host.go
pkg/utils/topology/pd.go
pkg/utils/topology/store.go
pkg/utils/topology/tidb.go
pkg/utils/topology/topology.go
ui/lib/apps/ClusterInfo/components/DiskTable.tsx
ui/lib/apps/ClusterInfo/components/HostTable.tsx
ui/lib/apps/ClusterInfo/components/Statistics.module.less
ui/lib/apps/ClusterInfo/components/Statistics.tsx
ui/lib/apps/ClusterInfo/components/StoreLocationTree/index.tsx
ui/lib/apps/ClusterInfo/pages/List.tsx
ui/lib/apps/ClusterInfo/translations/en.yaml
ui/lib/apps/ClusterInfo/translations/zh.yaml

Separate hosts and disks:
Provide statistics (fix #659 ):
Fixed bugs that disks instance may be incorrect.

clusterinfo: Refine

---

ui/lib/apps/InstanceProfiling/pages/Detail.tsx
ui/lib/apps/SearchLogs/components/SearchResult.tsx
ui/lib/apps/SlowQuery/components/SlowQueriesTable.tsx
ui/lib/apps/SlowQuery/pages/Detail/index.tsx
ui/lib/apps/Statement/components/StatementsTable.tsx
ui/lib/apps/Statement/pages/Detail/index.tsx
ui/lib/components/CardTable/index.tsx

This is a workaround for https://github.com/pingcap/tidb-dashboard/issues/641 to improve UX without changing too many codebase.
However most ideally we should implement page memorization and bring back "Back" again.
Also fixes https://github.com/pingcap/tidb-dashboard/issues/796

ui: Open statement and slow log in new tab

---

ui/lib/apps/SlowQuery/pages/Detail/DetailTabTime.tsx
ui/lib/apps/SlowQuery/translations/en.yaml
ui/lib/apps/SlowQuery/translations/zh.yaml
ui/lib/utils/tableColumns.tsx

Also, some descriptions are long so that a tooltip is added.

slow_log: Improve descriptions

---

ui/lib/components/MetricChart/index.tsx

Instead of changing the format library or removing duplicate labels, it is much simpler to just increase the precision
close #821

fix duplicated y-axis label

---

pkg/apiserver/statement/queries.go

It is caused by https://github.com/pingcap/tidb/pull/21286, which is compatible with MySQL 5.7. 
So I just change the query SQL.

fix issue of query topn statement get error

---

ui/lib/apps/SlowQuery/pages/Detail/DetailTabTime.tsx
ui/lib/apps/SlowQuery/translations/en.yaml
ui/lib/apps/SlowQuery/translations/zh.yaml
ui/lib/components/TextWithInfo/index.tsx
ui/lib/utils/tableColumns.tsx

show indents for slow query detail time more elegantly

---

ui/lib/apps/ClusterInfo/components/StoreLocation.tsx
ui/lib/apps/ClusterInfo/components/StoreLocationTree/index.tsx
ui/lib/apps/ClusterInfo/translations/en.yaml
ui/lib/apps/ClusterInfo/translations/zh.yaml

close issue #833 
What did:
- Differ TiFlash and TiKV nodes by different text and color (maybe we can choose a better color)
- Make reload really work
- Change tooltip to the text which always shows
Effect:

Diff tikv tiflash

---

pkg/apiserver/slowquery/queries.go

convert slow query list SQL from:
```sql
SELECT Digest, ...... ORDER BY timestamp DESC LIMIT 100
```
to 
```sql
SELECT Digest, ...... ORDER BY Time DESC LIMIT 100
```
The related query plan change from 
```sql
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ …
```

optimize slow-query list performance

---

pkg/keyvisual/decorator/tidb_requests.go

* keyviz: fix the bug that table info cannot be obtained if the database name contains special chars.
* Before:
* ![image](https://user-images.githubusercontent.com/19789302/103658101-bd5b2f80-4fa5-11eb-9a27-12e2f1cf7016.png)
* After:
* ![image](https://user-images.githubusercontent.com/19789302/103658169-d4018680-4fa5-11eb-9996-bbc3fe574161.png)

keyviz: fix the bug that sometimes the table info cannot be obtained

---

ui/lib/apps/SlowQuery/components/SlowQueriesTable.tsx
ui/lib/apps/SlowQuery/index.tsx
ui/lib/apps/SlowQuery/utils/useSlowQueryTableController.ts
ui/lib/apps/Statement/components/StatementsTable.tsx
ui/lib/apps/Statement/index.tsx
ui/lib/apps/Statement/utils/useStatementTableController.ts
ui/lib/components/CardTable/index.module.less
ui/lib/components/CardTable/index.tsx
ui/lib/utils/useCacheItemIndex.ts

Related PR: #828 
What did:
- Remember the last coarse scrolled position (in fact the clicked row) in the statements table, restore the position when coming back from the detail page
Effect:
How it implemented:
Because I didn't find a good way to remember and recover the exactly scrolled position for the statements table, I found the fluent UI DetailsList has a [initialFocusedIndex](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist) props that can make the list scroll to the target row when initializing. So we can remember the row index when clicking it. (Later found the initialFocusedIndex doesn't work well when the index is large, it needs the item is already rendered before scrolling to. Replace it with `scrollToIndex()` method and works well.)
When coming back …

remember the coarse scrolled position for statements and slow queries list

---

pkg/apiserver/slowquery/queries.go

1. revert #835
2. Only convert to `ORDER BY TIME` when the original is `ORDER BY timestamp`

fix slow query bug when order by other fields

---

pkg/config/dynamic_config_manager.go

* config: fix the bug that the dynamic config cannot be obtained when the PD starts later than the dashboard server
After the dashboard server is started, if the PD starts after 15 minutes, the dynamic config cannot be obtained normally and some services cannot be used. This PR fixes this bug.

config: fix the bug that sometimes the dynamic config cannot be obtained

---

ui/lib/apps/Statement/utils/useStatementTableController.ts

close #829 
- Set the initial loading statement to true
- Fix initial loading statement when queryStatementList
- Hide loading when catch errors

Fix(ui): Fix statemtent list initial loading

---

pkg/apiserver/clusterinfo/hostinfo/cluster_hardware.go
pkg/apiserver/clusterinfo/hostinfo/hostinfo.go
ui/lib/apps/ClusterInfo/components/HostTable.tsx
ui/lib/apps/ClusterInfo/translations/en.yaml
ui/lib/apps/ClusterInfo/translations/zh.yaml

Signed-off-by: Max-Cheng aaron9shire@gmail.com
What's Changed:
- Backend
- CPUinfo
- Frontend
- add new column specifically for the CPU Arch
- i18n

Feature: Display CPU arch

---

cmd/tidb-dashboard/main.go

This change proposes sending the client an HTTP 302 to `/dashboard` when the root path `/` is requested. This is a convenience feature useful for standalone/non-embedded TiDB dashboard deployments.

Redirect root path to UI handler at /dashboard

---

pkg/apiserver/apiserver.go
pkg/utils/sys_schema.go

Related: [pd/pull/3604](https://github.com/tikv/pd/pull/3604)
Cleanup ttl cache at end of lifecycle.

fix(ttlcache): goroutine leak

---

go.sum
pkg/keyvisual/decorator/tidb_requests.go
pkg/tidb/forwarder.go
pkg/utils/topology/tidb.go

close [tikv/pd#3612](https://github.com/tikv/pd/issues/3612)
* tidb: forwarder only uses tidb whose status is Up
* reduce warn log `fail to recv activity from remote, stay inactive and wait to next checking round`

tidb: forwarder only uses tidb whose status is Up

---

ui/lib/utils/useClientRequest.ts

Fix no-op warning comes from `useBatchClientRequest`.

fix(ui): setState after unmount in `useBatchClientRequest`

---

pkg/apiserver/slowquery/model.go
pkg/apiserver/statement/config.go
pkg/apiserver/statement/config_test.go
pkg/apiserver/statement/models.go
pkg/apiserver/statement/queries.go
pkg/apiserver/statement/service.go
pkg/apiserver/utils/gorm.go
ui/lib/apps/Statement/pages/List/StatementSettingForm.tsx
ui/lib/apps/Statement/pages/List/index.tsx
ui/lib/apps/Statement/translations/en.yaml
ui/lib/apps/Statement/translations/zh.yaml

feat(stmt): support config maximum number of stmt kept in memory

---

ui/lib/components/MetricChart/index.tsx

fix: label of y-axis is overflow

---

pkg/apiserver/slowquery/model.go
pkg/apiserver/slowquery/service.go
pkg/apiserver/statement/models.go
pkg/apiserver/statement/service.go
pkg/apiserver/statement/statement_gen.go
pkg/apiserver/utils/subset.go

Append ignored virtual fields to table_columns api. Then plan_count came back.

fix(stmt & slowquery): ignored virtual fields

---

ui/lib/apps/SlowQuery/pages/List/index.tsx
ui/lib/apps/SlowQuery/translations/en.yaml
ui/lib/apps/SlowQuery/translations/zh.yaml
ui/lib/apps/Statement/translations/en.yaml
ui/lib/apps/Statement/translations/zh.yaml

The placeholder description of the db selection in the slow query & stmt toolbar is ambiguous. Now unified with detail page.
Update:
`所有数据库` -> `执行数据库`
`All Databases` -> `Execution Databases`

tweak: slow query & stmt db select placeholder

---

cmd/tidb-dashboard/main.go

`NormalizePDEndPoint` is responsible for setting the URL scheme of the PD endpoint ([ref](https://github.com/pingcap/tidb-dashboard/blob/f6c50593b5de31cd2f2eeeaf9dbf33cf396cb4c2/pkg/config/config.go#L55)). However, it's currently called *before* `cfg.CoreConfig.ClusterTLSConfig` is set, which causes Dashboard to make plaintext HTTP requests to PD all the time, regardless of whether `--cluster-[ca|cert|key]` flags are set.
This change fixes the TLS origination behavior by running this logic *after* `cfg.CoreConfig.ClusterTLSConfig` is (optionally) populated by `buildTLSConfig`. This allows Dashboard to properly use HTTPS to PD when cluster TLS is enabled.
I didn't find any existing unit tests to cover this change, but if there's a test I can add or update to cover this, I'm happy to …

Fix endpoint scheme detection for TLS origination to PD

---

ui/lib/apps/DebugAPI/apilist/ApiForm.tsx
ui/lib/apps/DebugAPI/apilist/ApiList.tsx
ui/lib/apps/DebugAPI/apilist/widgets/Host.tsx
ui/lib/utils/i18n.ts

chore: add distro translation

---

Makefile
pkg/config/config.go
ui/dashboardApp/layout/signin/index.tsx
ui/dashboardApp/layout/translations/en.yaml
ui/dashboardApp/layout/translations/zh.yaml

What did:
- Make non-root-login start argument default value false
- Add tooltip to ask for upgrade TiDB to support login with non root users

Refine non root login

---

pkg/pd/client.go
pkg/tidb/client.go
pkg/tiflash/client.go
pkg/tikv/client.go

Close cache to avoid goroutine leaks.
Related PR: https://github.com/pingcap/tidb-dashboard/pull/994

fix(client): goroutine leaks

---

ui/config-overrides.js
ui/dashboardApp/layout/signin/index.tsx
ui/lib/utils/i18n.ts

How to build a distro dashboard:
1. Add the following code in the populate.go to pass the compile:
```
var Resource = map[string]string{
"tidb":    "TiDB",
"tikv":    "TiKV",
"tiflash": "TiFlash",
"pd":      "PD",
}
```
2. Build UI
```
UI=1 DISTRO_BUILD_TAG=1 make UI
```
3. Build all
```
UI=1 DISTRO_BUILD_TAG=1 make
```

hide help link for non TiDB distro

---

.github/workflows/release.yaml
pkg/apiserver/statement/queries.go
release-version
ui/lib/apps/Statement/components/StatementsTable.tsx
ui/lib/apps/Statement/utils/tableColumns.tsx
ui/lib/components/CardTable/index.tsx

We will lock the tidb-dashboard version of the old tidb version until it is fully tested and refined.
A separate tidb-dashboard version `release-5.2` is needed to fix the Statement display issue due to the table definition changes in tidb 5.2.

Release v2021.09.02.r52.1 init

---

.golangci.yml
pkg/apiserver/clusterinfo/service.go
pkg/apiserver/configuration/router.go
pkg/apiserver/conprof/service.go
pkg/apiserver/debugapi/service.go
pkg/apiserver/diagnose/diagnose.go
pkg/apiserver/info/info.go
pkg/apiserver/logsearch/service.go
pkg/apiserver/metrics/router.go
pkg/apiserver/profiling/router.go
pkg/apiserver/queryeditor/service.go
pkg/apiserver/slowquery/service.go
pkg/apiserver/statement/service.go
pkg/apiserver/user/auth.go
pkg/apiserver/user/code/router.go
pkg/apiserver/user/sso/router.go
pkg/keyvisual/manager.go
pkg/keyvisual/service.go

In https://github.com/pingcap/tidb-dashboard/pull/1052 we incorrectly added a dot suffix to all annotations. This PR reverted it back and added exclude rules to the linter.

Refactor: Fix godot incorrectly add dot suffix to annotations

---

util/topo/pd.go

Signed-off-by: crazycs <chen.two.cs@gmail.com>
```go
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18a874d]
goroutine 122 [running]:
testing.tRunner.func1.2(0x1c59c20, 0x2690700)
/Users/cs/code/goread/src/github.com/golang/go/src/testing/testing.go:1144 +0x332
testing.tRunner.func1(0xc000198300)
/Users/cs/code/goread/src/github.com/golang/go/src/testing/testing.go:1147 +0x4b6
panic(0x1c59c20, 0x2690700)
/Users/cs/code/goread/src/github.com/golang/go/src/runtime/panic.go:965 +0x1b9
github.com/pingcap/tidb-dashboard/util/topo.GetPDInstances(0xc00069c148, 0x0, 0x26e2578, 0x0, 0x0, 0x0) …
```

fix potential panic when GetPDInstances

---

scripts/distro/write_strings.sh
scripts/embed_ui_assets.sh
scripts/generate_assets.go

The root cause is that, as we are now introducing `go.mod` to the `scripts` directory, `go run` must run inside that directory in order to use its go.mod.

Fix script to embed the ui

---

ui/.prettierignore
ui/lib/distro_strings.json

Since the distro_strings.json is generated by scripts when dev, there is no need for prettier to check and fmt.

fix(distro): check distro_strings.json fmt by prettier

---

scripts/embed_ui_assets.sh
scripts/generate_assets.go

What did:
- Fix `scripts/generate_assets.go` crash when building by `DASHBOARD=COMPILE make pd-server` in pd repo

fix generate assets

---

pkg/apiserver/slowquery/service.go

Query slowquery detail will return: `No database selected`
This bug was introduced by add integration test:
https://github.com/pingcap/tidb-dashboard/pull/1083/files#diff-d0511bdf3eb8b77043a7cb8623422847e3e3d5dc5c033dbd63616a52cd8b1131L107-L108
https://github.com/pingcap/tidb-dashboard/pull/1083/files#diff-0a7ec858724330a3973a9ecac7cfa0699ca7d5c6231b5e68d4207d8331fadff0R97-R98

fix: select slowquery from slowquery table

---

pkg/apiserver/profiling/fetcher.go

We need to ignore `TIDB_OVERRIDE_STATUS_ENDPOINT` env var when profiling so that we can profile the correct target even if `TIDB_OVERRIDE_STATUS_ENDPOINT` is set.

fix: ignore override tidb endpoint when profiling

---

.golangci.yml
ui/lib/apps/ContinuousProfiling/pages/Detail.tsx
ui/lib/apps/InstanceProfiling/pages/Detail.tsx

What this PR did?
1. Remove extra rows for instances with empty tasks.
2. There is a cross browser compatibility about hashtag. The profile URL with hashtag works unstable on safari. Sometimes different profile URLs load the same speedscope page, which is the previous loaded speedscope page.  The URL with tashtag has following behaviors on different browsers:
`www.example.com#item`: this hashtag works fine on firefox and chrome, but work unstable on safari.
`www.example.com/#item`: url with a back slash before hashtag works fine on firefox, chrome and safari.
This issue can also be referred [here](https://stackoverflow.com/questions/18663410/safari-ignoring-removing-anchors-or-hashtags-when-clicking-hyperlinks/24778997#24778997)

fix: add a slash (/) before the hashtag for cross browser compatibility.

---

pkg/apiserver/diagnose/diagnose.go
ui/dashboardApp/layout/main/Sider/index.tsx
ui/lib/apps/ContinuousProfiling/pages/List.tsx
ui/lib/apps/SystemReport/pages/ReportGenerator.tsx
ui/lib/apps/SystemReport/translations/en.yaml
ui/lib/apps/SystemReport/translations/zh.yaml
ui/yarn.lock

What did:
- Hide "diagnose" app, it's not GA yet
- Rename "System Report" back to "Cluster Diagnostic"
- Add metrics relationship graph feature back (added in PR #760 and not cherry-pick back to the master)
- Disable control form if conprof is disabled
Screeshots:

Fix release

---

Makefile
ui/lib/client/baseUrl.ts

When a user develops TiDB dashboard in a remote machine and accesses the frontend page in the local, he will get the following error by accessing `http://{remote_addr}:3001/dashboard` in the local browser: 
Because the frontend can't access the backend API by `http://127.0.0.0:12333/dashboard/api`.
Solutions:
1. Forward local port 12333 to the remote, for example: `ssh -L 12333:locahost:12333 remote_addr`. 
1. Run TiDB dashboard backend by `bin/tidb-dashboard --host 0.0.0.0` and set `REACT_APP_DASHBOARD_API_URL=http://{remote_addr}:12333` in the `.env` file
1. Run TiDB dashboard backend by `bin/tidb-dashboard --host 0.0.0.0` and use `http://${window.location.hostname}:12333/dashboard` instead of `http://127.0.0.01:12333/dashboard` as API addr prefix.
This PR implements solution 3, and I …

make more convinient for developing in the remote machine

---

ui/lib/apps/ContinuousProfiling/pages/Detail.tsx

The issue is:
Two different profiling results of one component have same Flame Graph on Speedscope, this caused by the same issue, which had been fixed [here](https://github.com/pingcap/tidb-dashboard/pull/1123).

fix: conProf Profile URL

---

ui/builder.js

The build process for dev will exit unexpectedly when rebuild meets errors because we don't catch the error, we can reproduce it by deleting a necessary file.

fix dev build exit unexpectedly

---

ui/lib/components/Descriptions/index.module.less

Since the `<pre>` tag is inside a table row, and `overflow: auto` not working in table when using FireFox, we need to add a div inside table td with attribute `overflow: auto`. 
A reference about this issue can be checked [here](https://stackoverflow.com/questions/16328233/overflow-auto-does-not-work-in-firefox).

fix: solve overflow doesn't work on FireFox

---

ui/lib/apps/ContinuousProfiling/pages/ConProfSettingForm.tsx
ui/lib/apps/KeyViz/components/KeyVizSettingForm.tsx
ui/lib/apps/Statement/pages/List/StatementSettingForm.tsx
ui/lib/apps/TopSQL/pages/List/SettingsForm.tsx
ui/lib/components/DrawerFooter/index.module.less
ui/lib/components/DrawerFooter/index.tsx
ui/lib/components/index.ts
ui/package.json
ui/yarn.lock

When settings form overflows:
When settings form overflows and scrolled to the bottom:
When settings form does not overflow:

feat: Sticky submission area for Settings forms

---

ui/builder.js
ui/gulpfile.esm.js
ui/lib/client/index.tsx
ui/openapitools.json
ui/package.json
ui/yarn.lock

The following dependencies are bumped to the latest:
- @openapitools/openapi-generator-cli
- esbuild
- typescript

misc: bump ts related dependencies

---

ui/lib/apps/SearchLogs/components/SearchProgress.tsx
ui/lib/apps/SearchLogs/pages/LogSearchDetail.tsx
ui/lib/apps/SearchLogs/translations/en.yaml
ui/lib/apps/SearchLogs/translations/zh.yaml

Now it is possible to view logs in nearly full screen:

feat: enlarge log display area

---

ui/lib/apps/InstanceProfiling/pages/List.tsx
ui/lib/apps/InstanceProfiling/translations/en.yaml
ui/lib/apps/InstanceProfiling/translations/zh.yaml
ui/lib/components/InstanceSelect/DropOverlay.tsx
ui/lib/components/MultiSelect/DropOverlay.tsx

User only needs to click "Start Profiling"! No need to select multiple options any more.
This is a small feature extracted from https://github.com/pingcap/tidb-dashboard/pull/1148

feat: select all profiling types and instances by default

---

scripts/pd_version_matrix.go

This ignores tags such as "v1.2.3-rc" in the [Version Matrix](https://github.com/pingcap/tidb-dashboard/wiki/TiDB-Dashboard-×-PD-Version-Matrix).

script: ignore non-formal pd tags

---

ui/dashboardApp/index.tsx
ui/dashboardApp/layout/translations/en.yaml
ui/dashboardApp/layout/translations/zh.yaml
ui/lib/apps/Ngm/components/Error/NgmNotStarted.tsx

This change will be carried in v6.1.1.

ui: Add help link for ngm error

---

ui/package.json

According to https://pnpm.io/filtering#--filter-package_name-1, we can run the command only on the filtered package and all of its dependencies.

refine: build scenes

---

ui/packages/tidb-dashboard-for-dbaas/package.json
ui/packages/tidb-dashboard-for-dbaas/src/apps/Monitoring/metricsQueries.ts
ui/packages/tidb-dashboard-for-debugportal/package.json
ui/packages/tidb-dashboard-for-debugportal/src/apps/Monitoring/metricsQueries.ts
ui/packages/tidb-dashboard-for-op/src/apps/Monitoring/metricsQueries.ts

**What this PR does?**
Update TiDB server disconnection promQL
before:
after:

fix: TiDB server disconnection promQL

---

ui/packages/tidb-dashboard-for-dbaas/package.json
ui/packages/tidb-dashboard-lib/src/apps/KeyViz/heatmap/chart.ts

Preview:
time for UTC+00:00 timezone while local time is 17:35

fix keyviz tooltip timezone

---

ui/packages/tidb-dashboard-for-clinic-cloud/package.json
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Monitoring/context.ts
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Monitoring/metricsQueries.ts
ui/packages/tidb-dashboard-for-dbaas/package.json
ui/packages/tidb-dashboard-for-dbaas/src/apps/Monitoring/context.ts
ui/packages/tidb-dashboard-for-dbaas/src/apps/Monitoring/metricsQueries.ts
ui/packages/tidb-dashboard-for-op/package.json
ui/packages/tidb-dashboard-for-op/src/apps/Monitoring/context.ts
ui/packages/tidb-dashboard-for-op/src/apps/Monitoring/metricsQueries.ts
ui/packages/tidb-dashboard-lib/src/apps/Monitoring/components/Monitoring.tsx
ui/packages/tidb-dashboard-lib/src/apps/Monitoring/context/index.ts
ui/pnpm-lock.yaml

What this PR does:
- make promql version compatible
`version >= 5.4.1`, promql: `sum(tikv_store_size_bytes{type="used"}) by (instance)`
`version < 5.4.1`, promql: `sum(tikv_engine_size_bytes) by (instance)`
-  update TiFlash IO MBps: add `by (instance)` for each sum operation
- Sync metricsQueries of `tidb-dashboard-for-clinic-cloud` with the one of `tidb-dashboard-for-dbaas`.

chore: make tikv storage size version compatible

---

ui/packages/tidb-dashboard-for-clinic-cloud/package.json
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Overview/context.ts
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Overview/metricsQueries.ts
ui/packages/tidb-dashboard-for-op/src/apps/Overview/context.ts
ui/packages/tidb-dashboard-for-op/src/apps/Overview/metricsQueries.ts
ui/packages/tidb-dashboard-lib/src/apps/Overview/components/Metrics.tsx
ui/packages/tidb-dashboard-lib/src/apps/Overview/context/index.ts

**What this PR does:**
Currently, the overview app is applied to `tidb-dashboard-for-op` and `tidb-dashboard-for-clinic-cloud`, the promql is vary by variants, so load different promql to corresponding variant.

chore: load promql by op and cloud variant type

---

ui/packages/tidb-dashboard-for-dbaas/package.json
ui/packages/tidb-dashboard-lib/src/apps/Monitoring/components/Monitoring.tsx

- Add the missed timezone info back for monitoring chart

fix: add metrics chart timezone info back

---

ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/utils/useSlowQueryTableController.ts
ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/utils/useStatementTableController.ts

If the column used for order changes to be invisible, then reset the order column.

support reset order for statement and slow query

---

ui/packages/tidb-dashboard-for-clinic-cloud/package.json
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/DebugAPI/context.ts
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Statement/context.ts
ui/packages/tidb-dashboard-for-clinic-cloud/src/client/index.tsx
ui/packages/tidb-dashboard-for-dbaas/package.json
ui/packages/tidb-dashboard-for-dbaas/src/apps/Monitoring/context.ts
ui/packages/tidb-dashboard-for-dbaas/src/apps/Statement/context.ts
ui/packages/tidb-dashboard-for-dbaas/src/client/index.tsx
ui/packages/tidb-dashboard-for-op/src/apps/DebugAPI/context.ts
ui/packages/tidb-dashboard-for-op/src/apps/Statement/context.ts
ui/packages/tidb-dashboard-for-op/src/client/index.tsx
ui/packages/tidb-dashboard-for-op/src/dashboardApp/layout/signin/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/DebugAPI/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/DebugAPI/translations/zh.yaml
ui/packages/tidb-dashboard-lib/src/apps/Statement/context/index.ts
ui/packages/tidb-dashboard-lib/src/apps/Statement/utils/useStatementTableController.ts

Make new ui can work with old tidb-dashboard backend
- improve compatibility for statement, work with old tidb-dashboard backend early to at least 5.0.0
- improve compatibility for debug api, work with old-tidb-dashboard backend early to 5.0.3
- improve compatibility for sign in
statement changes its api by PR #1234 , brings to >=5.4.2 and >=6.1.0
debug api is first introduced in 5.0.0 and changes its api in 5.0.3 ( by PR #927 ) and 5.4.0 ( by PR #1103 )

refine: improve compatibility

---

ui/packages/tidb-dashboard-for-clinic-cloud/package.json
ui/packages/tidb-dashboard-for-clinic-cloud/src/client/index.tsx
ui/packages/tidb-dashboard-for-dbaas/src/client/index.tsx
ui/packages/tidb-dashboard-for-op/src/client/index.tsx

- Fix client setting for tidb-dashboard-for-clinic-cloud, fix the wrong final api path
- Refine client setting for other variant, dismiss duplicated setting for basePath
Related PR: #1431

refine: client init

---

.github/workflows/test-docker-image.yaml
.github/workflows/test.yaml
CONTRIBUTING.md
Dockerfile
Makefile
cmd/tidb-dashboard/main.go
docker-compose.yml
ui/packages/tidb-dashboard-for-op/cypress/integration/topsql/topsql.without_ngm_spec.js

- disable always-fail ngm e2e test;
- add docker image;
- add descriptions for tls command-line arguments;

Docker image support and misc. improvements

---

ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/DiskTable.tsx
ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/HostTable.tsx
ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/translations/zh.yaml

close #926 
- Update tooltip when failed to get host info, because the reason is not correct in some cases

chore: update tooltip when failed to get host info

---

ui/packages/tidb-dashboard-for-op/src/apps/Statement/context.ts
ui/packages/tidb-dashboard-for-op/src/client/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/context/index.ts
ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/PlanBind.module.less
ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/PlanBind.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/zh.yaml

- show plan bind status on statement detail page.
- provide a `Plan Binding` button on statement detail page.
- users are able to bind/drop a specific plan on a SQL.

Add one-click bind plan on sql statement detail page

---

ui/packages/tidb-dashboard-for-clinic-cloud/package.json
ui/packages/tidb-dashboard-for-op/src/apps/SlowQuery/context.ts
ui/packages/tidb-dashboard-for-op/src/apps/Statement/context.ts
ui/packages/tidb-dashboard-lib/src/apps/Monitoring/components/Monitoring.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/context/index.ts
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/zh.yaml
ui/packages/tidb-dashboard-lib/src/apps/Statement/context/index.ts
ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/zh.yaml

1. Make slow query list page remember the filter options again when jumping back from detail page
2. Update wording "Get 24 results" to "24 results"
3. Reduce the spacing between toolbar and result
4. Support config whether do instant query
5. Support to limit the slow query time range picker range

chore: slow query and statements apps refines

---

pkg/apiserver/clusterinfo/hostinfo/cluster_config.go
pkg/apiserver/clusterinfo/hostinfo/cluster_hardware.go

Removed hacking logic for tiflash in FillFromClusterHardwareTable(). Added the same logic for tiflash like pd, tikv and tidb in FillInstances().

Fixed issue #1505: Wrong disk mount directory of TiFlash

---

pkg/utils/topology/store.go

tiflash has three kinds of roles:
1. WriteNode: with label: <engine, tiflash> && <engine_role, write>
2. ComputeNode: with label: <engine, tiflash_compute>
3. Coupled TiFlash: with label <engine, tiflash>
For now, dashboard treat ComputeNode as TiKV, so need to fix.
Before: treat 127.0.0.1:3933 as TiKV
After:

distinguish tiflash_compute node

---

pkg/apiserver/slowquery/service.go

close: #1515 
Fix the issue where parsing the binary plan results in an error and return 500 in such cases.

slowquery: fix 500 when parsing binary plan fails

---

ui/packages/tidb-dashboard-for-op/src/dashboardApp/layout/main/Sider/index.tsx

Now the `Resource Manger` app entry shows for every TiDB version, that's not correct, it should only show for the TiDB version that support resource manger feature, aka >= 7.1.0

fix: make Resource Manager entry show correctly

---

ui/packages/tidb-dashboard-for-clinic-cloud/src/dashboardApp/layout/main/Sider/index.tsx

Temporary hide this feature entry because it may cause TiKV / TiFlash crash in some cases, will bring it back after fixing.

chore: hide system report for clinic cloud

---

scripts/_inc/run_services.sh

close #1547
because if this pr https://github.com/pingcap/tiup/pull/2163/files#diff-db646158ed09e3000e878361e90161269ce3141eb9c8311adec4fc32b036dbbeR923 had modified `CLUSTER START SUCCESSFULLY` to `TiDB Cluster is started`
And for master now is `TiDB Playground Cluster is started`
https://github.com/pingcap/tiup/blob/master/components/playground/playground.go#L978

ci: fix `run_services.sh` for tiup

---

cmd/tidb-dashboard/main.go

tweak: allows custom names to pass tls verification

---

pkg/apiserver/conprof/service.go
ui/packages/tidb-dashboard-client/src/client/api/models/conprof-component-num.ts
ui/packages/tidb-dashboard-client/swagger/spec.json
ui/packages/tidb-dashboard-for-clinic-cloud/src/utils/distro/strings_res.json
ui/packages/tidb-dashboard-for-op/src/utils/distro/strings_res.json
ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/DiskTable.tsx
ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/HostTable.tsx
ui/packages/tidb-dashboard-lib/src/apps/ContinuousProfiling/pages/List.tsx
ui/packages/tidb-dashboard-lib/src/client/models.ts
ui/packages/tidb-dashboard-lib/src/components/InstanceSelect/ValueDisplay.tsx
ui/packages/tidb-dashboard-lib/src/utils/instanceTable.ts
util/distro/distro.go

This PR supports to view TiCDC conprof status.
~~TODO: test compatibility with old versions (7.1, 6.5. 6.1)~~
Test in 7.3.0, 7.1.0, 6.5.3, 6.1.0.
6.1.0 doesn't show TiCDC component in conprof, because the ngm of this version doesn't support TiCDC.
others all show TiCDC component in conprof.
Run dev env:
```
$ tiup playground 
$ tiup cdc server --addr 127.0.0.1:8301
```
The cluster and cdc are both 7.3.0 version.
**Note:**  in my test environment, the ngm can't get the TiCDC profiles successfully, don't know why, so in the above screenshot, the status is `Partial Finished`, and in the detail page, the status for `TiCDC` is `Error`, clicking the `Error Information`, it will show the error reason in the modal.

feat(conprof): show conprof download link for TiCDC

---

pkg/apiserver/conprof/service.go
pkg/apiserver/resource_manager/service.go
pkg/apiserver/statement/queries.go

- Two SQL injection vulnerabilities
- The middleware is not aborted after JWT validation failure

security fixes

---

util/rest/context_helpers.go
util/rest/error_resp.go

We have been returning the full stack traces to the frontend, however this is not necessary, especially since they may reveal some internal information.

hide full stacktrace info in error message

---

pkg/apiserver/statement/models.go
ui/packages/tidb-dashboard-client/src/client/api/models/statement-model.ts
ui/packages/tidb-dashboard-client/swagger/spec.json
ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/PlanDetailTabBasic.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/zh.yaml
ui/packages/tidb-dashboard-lib/src/apps/Statement/utils/tableColumns.tsx
ui/packages/tidb-dashboard-lib/src/client/models.ts

feat(statements): show `plan_cache_hits` field

---

pkg/apiserver/profiling/pprof.go

tweak: make the goroutine profile more verbose

---

pkg/apiserver/user/sso/router.go
pkg/config/dynamic_config_manager.go
ui/packages/tidb-dashboard-lib/src/apps/UserProfile/components/Form.SSO.tsx
ui/packages/tidb-dashboard-lib/src/apps/UserProfile/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/UserProfile/translations/zh.yaml

Related PR: https://github.com/pingcap/tidb-dashboard/pull/1567, it adds support for "Client Secret Post" authentication method. (When you create a `regular web app` in auth0 console, it uses the "Client Secret Post" authentication method).
This PR handle the compatibility with old version, and hide the client secret for security.
1. Login [Auth0](https://auth0.com/) by google account
2. Create a "Regular Web App" and "Single Web App" applications in the Auth0
4. Set the `Allowed Callback URLs` and `Allowed Logout URLs` for the above applications, following the steps in the https://docs.pingcap.com/tidb/stable/dashboard-session-sso#example-2-use-auth0-for-tidb-dashboard-sso-sign-in
6. In tidb-dashboard, go to sso configuration page, fill the `OIDC Client ID`. If the `Client ID` comes from …

chore(sso): improve client secret security

---

ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
ui/packages/tidb-dashboard-lib/src/apps/Monitoring/components/Monitoring.tsx
ui/packages/tidb-dashboard-lib/src/apps/Overview/components/Metrics.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/TopSQL/context/index.ts
ui/packages/tidb-dashboard-lib/src/apps/TopSQL/pages/List/List.tsx
ui/packages/tidb-dashboard-lib/src/components/LimitTimeRange/index.tsx
ui/packages/tidb-dashboard-lib/src/components/index.ts

- show org name and user name in TopSQL for clinic variant
- limit time range to 1 day in TopSQL for clinic variant

chore(topsql): adjust TopSQL for clinic

---

pkg/tidb/client.go

close: https://github.com/pingcap/tidb-dashboard/issues/1604
This PR explicitly sets the session-level `max_execution_time` to avoid being affected by the global-level `max_execution_time`.

tweak: explicitly set session max_execution_time to 600s

---

pkg/apiserver/profiling/router.go

reuse `convertDotToSVG` to avoid the dependency of `graphviz` in env

profiling: reuse convertDotToSVG to generate tikv heap profile svg

---

util/testutil/testdefault/main.go

Ignore `github.com/ReneKroon/ttlcache/v2.(*Cache).startExpirationProcessing`

chore: fix goleak check

---

cmd/tidb-dashboard/main.go
pkg/apiserver/profiling/fetcher.go
pkg/apiserver/profiling/jeprof.in
pkg/config/config.go
pkg/tikv/client.go

Fix https://github.com/pingcap/tidb-dashboard/issues/1613
Fix it by passing the TLS certificate to jeprof. 
By the way, fix some potential issues in jeprof:
- Join the port to jeprof temporarily file name, otherwise multiple instances deployed in the same host may write to same temp file
- Clean up collected profile files when finished instead of keeping them
Manual Test:

profiling: Pass the TLS certificate to jeprof

---

pkg/apiserver/apiserver.go
pkg/apiserver/clusterinfo/host.go
pkg/apiserver/clusterinfo/service.go
pkg/apiserver/clusterinfo/statistics.go
pkg/apiserver/debugapi/endpoint/payload.go
pkg/apiserver/model/common_models.go
pkg/utils/topology/models.go
pkg/utils/topology/ticdc.go
pkg/utils/topology/tidb.go
util/client/ticdcclient/status_client.go
util/topo/model.go

add ticdc topology in apiserver

---

ui/packages/tidb-dashboard-for-clinic-cloud/src/dashboardApp/layout/main/Sider/Banner.tsx
ui/packages/tidb-dashboard-for-op/src/dashboardApp/layout/main/Sider/Banner.tsx

This PR fixes the following error which has duplicated `v` in version showing in the banner:

fix: remove duplicated `v` in version showing in the banner

---

ui/packages/tidb-dashboard-for-clinic-cloud/public/ngm.html
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/SlowQuery/context.ts
ui/packages/tidb-dashboard-for-clinic-op/src/apps/SlowQuery/context.ts
ui/packages/tidb-dashboard-for-dbaas/src/apps/SlowQuery/context.ts
ui/packages/tidb-dashboard-for-op/src/apps/SlowQuery/context.ts
ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/InstanceTable.tsx
ui/packages/tidb-dashboard-lib/src/apps/Overview/components/Instances.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/context/index.ts
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/zh.yaml
ui/packages/tidb-dashboard-lib/src/apps/TopSQL/components/Filter/InstanceSelect.tsx

1. Support search slow query by digest filter
2. Expand the TopSQL select instances component width
3. Handle the compatibility issues when querying TiCDC and TiProxy components under TiDB 7.6.0

feat(slow-query): support slow query search by digest

---

pkg/apiserver/statement/models.go
ui/packages/tidb-dashboard-client/src/client/api/models/statement-model.ts
ui/packages/tidb-dashboard-client/swagger/spec.json
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Detail/DetailTabBasic.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Detail/DetailTabTime.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/PlanDetailTabBasic.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/PlanDetailTabTime.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/zh.yaml
ui/packages/tidb-dashboard-lib/src/apps/Statement/utils/tableColumns.tsx
ui/packages/tidb-dashboard-lib/src/client/models.ts

statement,slowquery: add request unit part in the detail page

---

pkg/apiserver/resource_manager/service.go
pkg/apiserver/slowquery/queries.go
ui/packages/tidb-dashboard-client/src/client/api/api/default-api.ts
ui/packages/tidb-dashboard-client/src/client/api/models/slowquery-get-list-request.ts
ui/packages/tidb-dashboard-client/swagger/spec.json
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/SlowQuery/context.ts
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Statement/context.ts
ui/packages/tidb-dashboard-for-clinic-op/src/apps/SlowQuery/context.ts
ui/packages/tidb-dashboard-for-op/src/apps/SlowQuery/context.ts
ui/packages/tidb-dashboard-for-op/src/apps/Statement/context.ts
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/context/index.ts
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/zh.yaml
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/utils/useSlowQueryTableController.ts
ui/packages/tidb-dashboard-lib/src/client/models.ts

support slow query search by resource group
- If there are above 2 resource groups in the cluster, will show the `MultiSelect`
- Add relative API
Example:

feat(slow-query): support slow query search by resource group

---

pkg/apiserver/statement/queries.go
pkg/apiserver/statement/service.go
ui/packages/tidb-dashboard-client/src/client/api/api/default-api.ts
ui/packages/tidb-dashboard-client/src/client/api/models/statement-get-statements-request.ts
ui/packages/tidb-dashboard-client/swagger/spec.json
ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/Statement/context.ts
ui/packages/tidb-dashboard-for-op/src/apps/Statement/context.ts
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/context/index.ts
ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/zh.yaml
ui/packages/tidb-dashboard-lib/src/apps/Statement/utils/useStatementTableController.ts
ui/packages/tidb-dashboard-lib/src/client/models.ts

support `statement` search by resource group
- If there are above 2 resource groups in the cluster, will show the `MultiSelect`
- Add relative API
Example:

feat(statements): support statement search by resource group

---

pkg/apiserver/clusterinfo/hostinfo/cluster_config.go

close: https://github.com/pingcap/tidb-dashboard/issues/1625
In the past, the data directory of tiflash was only obtained from `engine-store.path`. This PR modified it to be obtained from both `engine-store.path`, `engine-store.storage.main.dir` and `engine-store.storage.latest.dir`.

fix: correctly display the disk mount points of tiflash

---

pkg/apiserver/debugapi/apis.go
pkg/apiserver/debugapi/service.go

before fixing, the default file ext is `.bin`

fix(debug-data): fix the wrong file ext for tiproxy config

---

pkg/apiserver/clusterinfo/host.go
pkg/apiserver/clusterinfo/statistics.go
ui/packages/tidb-dashboard-lib/src/apps/ClusterInfo/components/Statistics.tsx

This PR fixes the following error pages:

fix(cluster_info): fix error for hosts/disks/statistics page

---

ui/packages/tidb-dashboard-for-clinic-cloud/src/apps/SlowQuery/context.ts
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/context/index.ts
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/DownloadDBFileModal.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/List/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/zh.yaml

Enable download slow query db file on slow query page in clinic-cloud.

feat(slow_query): download db file for slow query

---

pkg/apiserver/slowquery/queries.go
pkg/apiserver/slowquery/service.go
tests/integration/slowquery/mock_db_test.go
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/translations/zh.yaml
ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/en.yaml
ui/packages/tidb-dashboard-lib/src/apps/Statement/translations/zh.yaml

fix https://github.com/pingcap/tidb-dashboard/issues/1693
Test:

fix(slow-query): fix cannot show RU in slow query detail page

---

pkg/keyvisual/decorator/tidb_requests.go
pkg/tidb/model/model.go

If the TiDB kernel's API `/schema/<db>` supports new param `id_name_only`, then a batch strategy will be adopted, and only 512 tableinfos will be pulled in each batch.
Related PR: https://github.com/pingcap/tidb/pull/54608
Signed-off-by: mornyx <mornyx.z@gmail.com>

feat: support multi batches for keyviz schema data

---

pkg/apiserver/clusterinfo/hostinfo/cluster_config.go

fix for issue #1703
My change:
Inside function, Func FillInstances()
Add where clause ``OR (`TYPE` = 'ticdc' AND `KEY` = 'data-dir')"`` in the query to table INFORMATION_SCHEMA.CLUSTER_CONFIG.

dashboard/api/host/all: add ticdc instance information to host/all api

---

cmd/tidb-dashboard/main.go
pkg/apiserver/metrics/router.go
pkg/apiserver/metrics/service.go
pkg/apiserver/user/code/router.go
pkg/apiserver/user/code/service.go
pkg/config/config.go

- **add share code revoke api**: In the past, we could not revoke the authorization code obtained through "Share TiDB Dashboard Sessions" and could only wait for it to expire. I added a new API to revoke all authorization codes by resetting the key.
- **add a config to allow disabling custom prom addr**: For security reasons, we need to introduce a configuration item to disable the custom promtheus address to avoid SSRF attacks.

*: add share code revoke api; add a config to allow disabling custom prom addr 

---

ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/utils/useSlowQueryTableController.ts
ui/packages/tidb-dashboard-lib/src/apps/Statement/utils/useStatementTableController.ts

resource manager feature only works above 7.0.0 version, so we can ignore the error below 7.0.0 version.

chore(statement_slowquery): ignore resource manager api error

---

pkg/apiserver/clusterinfo/service.go

Explicitly check the alertmanager address passed by the frontend and ensure it matches the address stored in etcd.

clusterinfo: fix ssrf on /topology/alertmanager/{address}/count

---

pkg/apiserver/slowquery/service.go
pkg/apiserver/statement/service.go
ui/packages/tidb-dashboard-lib/src/apps/SlowQuery/pages/Detail/index.tsx
ui/packages/tidb-dashboard-lib/src/apps/Statement/pages/Detail/PlanDetail.tsx

fix: fix not show plan issue

---

pkg/apiserver/profiling/service.go
pkg/apiserver/statement/queries.go
pkg/httpc/client.go
pkg/tidb/client.go
pkg/tidb/proxy.go

ref: https://github.com/tikv/pd/issues/9402
goroutine profile:
```
goroutine profile: total 2916
681 @ 0xf61910 0xf60825 0xf922e5 0xf922c2 0xf91f33 0x11ee43f 0x11f00c8 0x11eeb10 0xf83007 0x231e0da 0x231e097 0xf46921
#	0xf6190f	syscall.Syscall6+0x2f							/usr/local/go/src/syscall/syscall_linux.go:91
#	0xf60824	syscall.Splice+0x44							/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1356
#	0xf922e4	internal/poll.splice+0x184						/usr/local/go/src/internal/poll/splice_linux.go:155
#	0xf922c1	internal/poll.spliceDrain+0x161						/usr/local/go/src/internal/poll/splice_linux.go:92
#	0xf91f32	internal/poll.Splice+0x172						/usr/local/go/src/internal/poll/splice_linux.go:42
#	0x11ee43e	net.splice+0xde								/usr/local/go/src/net/splice_linux.go:39
#	0x11f00c7	net.(*TCPConn).readFrom+0x27 …
```

Goroutine leak
